<?php
/**
 * AlertV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * AlertV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AlertV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'AlertV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'alertGroupIds' => 'string[]',
        'alertSourceId' => 'string',
        'attributes' => '\IncidentIo\Model\AlertAttributeEntryV2[]',
        'createdAt' => '\DateTime',
        'deduplicationKey' => 'string',
        'description' => 'string',
        'id' => 'string',
        'resolvedAt' => '\DateTime',
        'sourceUrl' => 'string',
        'status' => 'string',
        'tags' => '\IncidentIo\Model\AlertTagV2[]',
        'title' => 'string',
        'updatedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'alertGroupIds' => null,
        'alertSourceId' => null,
        'attributes' => null,
        'createdAt' => 'date-time',
        'deduplicationKey' => null,
        'description' => null,
        'id' => null,
        'resolvedAt' => 'date-time',
        'sourceUrl' => null,
        'status' => null,
        'tags' => null,
        'title' => null,
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'alertGroupIds' => false,
        'alertSourceId' => false,
        'attributes' => false,
        'createdAt' => false,
        'deduplicationKey' => false,
        'description' => false,
        'id' => false,
        'resolvedAt' => false,
        'sourceUrl' => false,
        'status' => false,
        'tags' => false,
        'title' => false,
        'updatedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'alertGroupIds' => 'alert_group_ids',
        'alertSourceId' => 'alert_source_id',
        'attributes' => 'attributes',
        'createdAt' => 'created_at',
        'deduplicationKey' => 'deduplication_key',
        'description' => 'description',
        'id' => 'id',
        'resolvedAt' => 'resolved_at',
        'sourceUrl' => 'source_url',
        'status' => 'status',
        'tags' => 'tags',
        'title' => 'title',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'alertGroupIds' => 'setAlertGroupIds',
        'alertSourceId' => 'setAlertSourceId',
        'attributes' => 'setAttributes',
        'createdAt' => 'setCreatedAt',
        'deduplicationKey' => 'setDeduplicationKey',
        'description' => 'setDescription',
        'id' => 'setId',
        'resolvedAt' => 'setResolvedAt',
        'sourceUrl' => 'setSourceUrl',
        'status' => 'setStatus',
        'tags' => 'setTags',
        'title' => 'setTitle',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'alertGroupIds' => 'getAlertGroupIds',
        'alertSourceId' => 'getAlertSourceId',
        'attributes' => 'getAttributes',
        'createdAt' => 'getCreatedAt',
        'deduplicationKey' => 'getDeduplicationKey',
        'description' => 'getDescription',
        'id' => 'getId',
        'resolvedAt' => 'getResolvedAt',
        'sourceUrl' => 'getSourceUrl',
        'status' => 'getStatus',
        'tags' => 'getTags',
        'title' => 'getTitle',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const STATUS_FIRING = 'firing';
    public const STATUS_RESOLVED = 'resolved';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_FIRING,
            self::STATUS_RESOLVED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('alertGroupIds', $data ?? [], null);
        $this->setIfExists('alertSourceId', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('deduplicationKey', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('resolvedAt', $data ?? [], null);
        $this->setIfExists('sourceUrl', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['alertSourceId'] === null) {
            $invalidProperties[] = "'alertSourceId' can't be null";
        }
        if ($this->container['attributes'] === null) {
            $invalidProperties[] = "'attributes' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['deduplicationKey'] === null) {
            $invalidProperties[] = "'deduplicationKey' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets alertGroupIds
     *
     * @return string[]|null
     */
    public function getAlertGroupIds(): ?array
    {
        return $this->container['alertGroupIds'];
    }

    /**
     * Sets alertGroupIds
     *
     * @param string[]|null $alertGroupIds The IDs of every alert group this alert belongs to. Empty when the alert is not part of any group.
     *
     * @return $this
     */
    public function setAlertGroupIds(?array $alertGroupIds): static
    {
        if (is_null($alertGroupIds)) {
            throw new InvalidArgumentException('non-nullable alertGroupIds cannot be null');
        }
        $this->container['alertGroupIds'] = $alertGroupIds;

        return $this;
    }

    /**
     * Gets alertSourceId
     *
     * @return string
     */
    public function getAlertSourceId(): string
    {
        return $this->container['alertSourceId'];
    }

    /**
     * Sets alertSourceId
     *
     * @param string $alertSourceId The ID of the alert source this alert fired on
     *
     * @return $this
     */
    public function setAlertSourceId(string $alertSourceId): static
    {
        if (is_null($alertSourceId)) {
            throw new InvalidArgumentException('non-nullable alertSourceId cannot be null');
        }
        $this->container['alertSourceId'] = $alertSourceId;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \IncidentIo\Model\AlertAttributeEntryV2[]
     */
    public function getAttributes(): array
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \IncidentIo\Model\AlertAttributeEntryV2[] $attributes Attribute values parsed from the alerts payload
     *
     * @return $this
     */
    public function setAttributes(array $attributes): static
    {
        if (is_null($attributes)) {
            throw new InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt When this entry was created
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets deduplicationKey
     *
     * @return string
     */
    public function getDeduplicationKey(): string
    {
        return $this->container['deduplicationKey'];
    }

    /**
     * Sets deduplicationKey
     *
     * @param string $deduplicationKey A deduplication key which uniquely references this alert from your alert source. For newly created HTTP sources, this field is required. If you send an event with the same deduplication_key multiple times, only one alert will be created in incident.io for this alert source config. You can filter on this field to find the alert created by an event you've sent us.
     *
     * @return $this
     */
    public function setDeduplicationKey(string $deduplicationKey): static
    {
        if (is_null($deduplicationKey)) {
            throw new InvalidArgumentException('non-nullable deduplicationKey cannot be null');
        }
        $this->container['deduplicationKey'] = $deduplicationKey;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the alert
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The ID of this alert
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets resolvedAt
     *
     * @return \DateTime|null
     */
    public function getResolvedAt(): ?\DateTime
    {
        return $this->container['resolvedAt'];
    }

    /**
     * Sets resolvedAt
     *
     * @param \DateTime|null $resolvedAt When this alert was resolved
     *
     * @return $this
     */
    public function setResolvedAt(?\DateTime $resolvedAt): static
    {
        if (is_null($resolvedAt)) {
            throw new InvalidArgumentException('non-nullable resolvedAt cannot be null');
        }
        $this->container['resolvedAt'] = $resolvedAt;

        return $this;
    }

    /**
     * Gets sourceUrl
     *
     * @return string|null
     */
    public function getSourceUrl(): ?string
    {
        return $this->container['sourceUrl'];
    }

    /**
     * Sets sourceUrl
     *
     * @param string|null $sourceUrl If applicable, a link to the alert in the upstream system
     *
     * @return $this
     */
    public function setSourceUrl(?string $sourceUrl): static
    {
        if (is_null($sourceUrl)) {
            throw new InvalidArgumentException('non-nullable sourceUrl cannot be null');
        }
        $this->container['sourceUrl'] = $sourceUrl;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus(): string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Statuses of an alert
     *
     * @return $this
     */
    public function setStatus(string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \IncidentIo\Model\AlertTagV2[]|null
     */
    public function getTags(): ?array
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \IncidentIo\Model\AlertTagV2[]|null $tags Tags someone has applied to this alert
     *
     * @return $this
     */
    public function setTags(?array $tags): static
    {
        if (is_null($tags)) {
            throw new InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle(): string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of the alert, parsed from the alert payload according to the alert source configuration
     *
     * @return $this
     */
    public function setTitle(string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt When this alert was last updated
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


