<?php
/**
 * APIKeyV1
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * APIKeyV1 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class APIKeyV1 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'APIKeyV1';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'comments' => 'string',
        'createdAt' => '\DateTime',
        'creator' => '\IncidentIo\Model\ActorV1',
        'id' => 'string',
        'lastUsedAt' => '\DateTime',
        'name' => 'string',
        'roles' => '\IncidentIo\Model\APIKeyRoleV1[]',
        'teamIds' => 'string[]',
        'teamRoles' => '\IncidentIo\Model\APIKeyTeamRoleV1[]',
        'tokenLastIssuedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'comments' => null,
        'createdAt' => 'date-time',
        'creator' => null,
        'id' => null,
        'lastUsedAt' => 'date-time',
        'name' => null,
        'roles' => null,
        'teamIds' => null,
        'teamRoles' => null,
        'tokenLastIssuedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'comments' => false,
        'createdAt' => false,
        'creator' => false,
        'id' => false,
        'lastUsedAt' => false,
        'name' => false,
        'roles' => false,
        'teamIds' => false,
        'teamRoles' => false,
        'tokenLastIssuedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'comments' => 'comments',
        'createdAt' => 'created_at',
        'creator' => 'creator',
        'id' => 'id',
        'lastUsedAt' => 'last_used_at',
        'name' => 'name',
        'roles' => 'roles',
        'teamIds' => 'team_ids',
        'teamRoles' => 'team_roles',
        'tokenLastIssuedAt' => 'token_last_issued_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'comments' => 'setComments',
        'createdAt' => 'setCreatedAt',
        'creator' => 'setCreator',
        'id' => 'setId',
        'lastUsedAt' => 'setLastUsedAt',
        'name' => 'setName',
        'roles' => 'setRoles',
        'teamIds' => 'setTeamIds',
        'teamRoles' => 'setTeamRoles',
        'tokenLastIssuedAt' => 'setTokenLastIssuedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'comments' => 'getComments',
        'createdAt' => 'getCreatedAt',
        'creator' => 'getCreator',
        'id' => 'getId',
        'lastUsedAt' => 'getLastUsedAt',
        'name' => 'getName',
        'roles' => 'getRoles',
        'teamIds' => 'getTeamIds',
        'teamRoles' => 'getTeamRoles',
        'tokenLastIssuedAt' => 'getTokenLastIssuedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('comments', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('lastUsedAt', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('teamIds', $data ?? [], null);
        $this->setIfExists('teamRoles', $data ?? [], null);
        $this->setIfExists('tokenLastIssuedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['comments']) && (mb_strlen($this->container['comments']) > 5000)) {
            $invalidProperties[] = "invalid value for 'comments', the character length must be smaller than or equal to 5000.";
        }

        if (!is_null($this->container['comments']) && !preg_match("/^[^ ]*$/", $this->container['comments'])) {
            $invalidProperties[] = "invalid value for 'comments', must be conform to the pattern /^[^ ]*$/.";
        }

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['creator'] === null) {
            $invalidProperties[] = "'creator' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['roles'] === null) {
            $invalidProperties[] = "'roles' can't be null";
        }
        if ($this->container['teamIds'] === null) {
            $invalidProperties[] = "'teamIds' can't be null";
        }
        if ($this->container['teamRoles'] === null) {
            $invalidProperties[] = "'teamRoles' can't be null";
        }
        if ($this->container['tokenLastIssuedAt'] === null) {
            $invalidProperties[] = "'tokenLastIssuedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets comments
     *
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string|null $comments Freeform notes about this API key
     *
     * @return $this
     */
    public function setComments(?string $comments): static
    {
        if (is_null($comments)) {
            throw new InvalidArgumentException('non-nullable comments cannot be null');
        }
        if ((mb_strlen($comments) > 5000)) {
            throw new InvalidArgumentException('invalid length for $comments when calling APIKeyV1., must be smaller than or equal to 5000.');
        }
        if ((!preg_match("/^[^ ]*$/", ObjectSerializer::toString($comments)))) {
            throw new InvalidArgumentException("invalid value for \$comments when calling APIKeyV1., must conform to the pattern /^[^ ]*$/.");
        }

        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt When the API key was created
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return \IncidentIo\Model\ActorV1
     */
    public function getCreator(): \IncidentIo\Model\ActorV1
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param \IncidentIo\Model\ActorV1 $creator creator
     *
     * @return $this
     */
    public function setCreator(\IncidentIo\Model\ActorV1 $creator): static
    {
        if (is_null($creator)) {
            throw new InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier for this API key
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets lastUsedAt
     *
     * @return \DateTime|null
     */
    public function getLastUsedAt(): ?\DateTime
    {
        return $this->container['lastUsedAt'];
    }

    /**
     * Sets lastUsedAt
     *
     * @param \DateTime|null $lastUsedAt When the key was last used to authenticate a request
     *
     * @return $this
     */
    public function setLastUsedAt(?\DateTime $lastUsedAt): static
    {
        if (is_null($lastUsedAt)) {
            throw new InvalidArgumentException('non-nullable lastUsedAt cannot be null');
        }
        $this->container['lastUsedAt'] = $lastUsedAt;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the API key, for the user's reference
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return \IncidentIo\Model\APIKeyRoleV1[]
     */
    public function getRoles(): array
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param \IncidentIo\Model\APIKeyRoleV1[] $roles The account-level roles assigned to this API key
     *
     * @return $this
     */
    public function setRoles(array $roles): static
    {
        if (is_null($roles)) {
            throw new InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets teamIds
     *
     * @return string[]
     */
    public function getTeamIds(): array
    {
        return $this->container['teamIds'];
    }

    /**
     * Sets teamIds
     *
     * @param string[] $teamIds IDs of teams that this API key is scoped to
     *
     * @return $this
     */
    public function setTeamIds(array $teamIds): static
    {
        if (is_null($teamIds)) {
            throw new InvalidArgumentException('non-nullable teamIds cannot be null');
        }
        $this->container['teamIds'] = $teamIds;

        return $this;
    }

    /**
     * Gets teamRoles
     *
     * @return \IncidentIo\Model\APIKeyTeamRoleV1[]
     */
    public function getTeamRoles(): array
    {
        return $this->container['teamRoles'];
    }

    /**
     * Sets teamRoles
     *
     * @param \IncidentIo\Model\APIKeyTeamRoleV1[] $teamRoles The team-level roles assigned to this API key
     *
     * @return $this
     */
    public function setTeamRoles(array $teamRoles): static
    {
        if (is_null($teamRoles)) {
            throw new InvalidArgumentException('non-nullable teamRoles cannot be null');
        }
        $this->container['teamRoles'] = $teamRoles;

        return $this;
    }

    /**
     * Gets tokenLastIssuedAt
     *
     * @return \DateTime
     */
    public function getTokenLastIssuedAt(): \DateTime
    {
        return $this->container['tokenLastIssuedAt'];
    }

    /**
     * Sets tokenLastIssuedAt
     *
     * @param \DateTime $tokenLastIssuedAt When the current token for this API was last issued. This is the last time the token was rotated, or when it was initially created. Older tokens may remain valid for up to an hour after they have been rotated, configured when you call the rotate endpoint.
     *
     * @return $this
     */
    public function setTokenLastIssuedAt(\DateTime $tokenLastIssuedAt): static
    {
        if (is_null($tokenLastIssuedAt)) {
            throw new InvalidArgumentException('non-nullable tokenLastIssuedAt cannot be null');
        }
        $this->container['tokenLastIssuedAt'] = $tokenLastIssuedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


