<?php
/**
 * AuditLogInvestigationTriggerMetadataV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * AuditLogInvestigationTriggerMetadataV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AuditLogInvestigationTriggerMetadataV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'AuditLogInvestigationTriggerMetadataV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'blocks' => 'string',
        'enabled' => 'string',
        'frequency' => 'string',
        'moment' => 'string',
        'pluginId' => 'string',
        'skill' => 'string',
        'taskSet' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'blocks' => null,
        'enabled' => null,
        'frequency' => null,
        'moment' => null,
        'pluginId' => null,
        'skill' => null,
        'taskSet' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'blocks' => false,
        'enabled' => false,
        'frequency' => false,
        'moment' => false,
        'pluginId' => false,
        'skill' => false,
        'taskSet' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'blocks' => 'blocks',
        'enabled' => 'enabled',
        'frequency' => 'frequency',
        'moment' => 'moment',
        'pluginId' => 'plugin_id',
        'skill' => 'skill',
        'taskSet' => 'task_set'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'blocks' => 'setBlocks',
        'enabled' => 'setEnabled',
        'frequency' => 'setFrequency',
        'moment' => 'setMoment',
        'pluginId' => 'setPluginId',
        'skill' => 'setSkill',
        'taskSet' => 'setTaskSet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'blocks' => 'getBlocks',
        'enabled' => 'getEnabled',
        'frequency' => 'getFrequency',
        'moment' => 'getMoment',
        'pluginId' => 'getPluginId',
        'skill' => 'getSkill',
        'taskSet' => 'getTaskSet'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blocks', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('frequency', $data ?? [], null);
        $this->setIfExists('moment', $data ?? [], null);
        $this->setIfExists('pluginId', $data ?? [], null);
        $this->setIfExists('skill', $data ?? [], null);
        $this->setIfExists('taskSet', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['blocks'] === null) {
            $invalidProperties[] = "'blocks' can't be null";
        }
        if ($this->container['enabled'] === null) {
            $invalidProperties[] = "'enabled' can't be null";
        }
        if ($this->container['frequency'] === null) {
            $invalidProperties[] = "'frequency' can't be null";
        }
        if ($this->container['moment'] === null) {
            $invalidProperties[] = "'moment' can't be null";
        }
        if ($this->container['taskSet'] === null) {
            $invalidProperties[] = "'taskSet' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blocks
     *
     * @return string
     */
    public function getBlocks(): string
    {
        return $this->container['blocks'];
    }

    /**
     * Sets blocks
     *
     * @param string $blocks Whether the investigation waits for the trigger to finish before moving on (true, false)
     *
     * @return $this
     */
    public function setBlocks(string $blocks): static
    {
        if (is_null($blocks)) {
            throw new InvalidArgumentException('non-nullable blocks cannot be null');
        }
        $this->container['blocks'] = $blocks;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return string
     */
    public function getEnabled(): string
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param string $enabled Whether the trigger fires (true, false)
     *
     * @return $this
     */
    public function setEnabled(string $enabled): static
    {
        if (is_null($enabled)) {
            throw new InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets frequency
     *
     * @return string
     */
    public function getFrequency(): string
    {
        return $this->container['frequency'];
    }

    /**
     * Sets frequency
     *
     * @param string $frequency How often the trigger fires across one investigation
     *
     * @return $this
     */
    public function setFrequency(string $frequency): static
    {
        if (is_null($frequency)) {
            throw new InvalidArgumentException('non-nullable frequency cannot be null');
        }
        $this->container['frequency'] = $frequency;

        return $this;
    }

    /**
     * Gets moment
     *
     * @return string
     */
    public function getMoment(): string
    {
        return $this->container['moment'];
    }

    /**
     * Sets moment
     *
     * @param string $moment When in an investigation the trigger runs
     *
     * @return $this
     */
    public function setMoment(string $moment): static
    {
        if (is_null($moment)) {
            throw new InvalidArgumentException('non-nullable moment cannot be null');
        }
        $this->container['moment'] = $moment;

        return $this;
    }

    /**
     * Gets pluginId
     *
     * @return string|null
     */
    public function getPluginId(): ?string
    {
        return $this->container['pluginId'];
    }

    /**
     * Sets pluginId
     *
     * @param string|null $pluginId The extension plugin holding the skill the trigger runs, absent for a trigger that only gives a task
     *
     * @return $this
     */
    public function setPluginId(?string $pluginId): static
    {
        if (is_null($pluginId)) {
            throw new InvalidArgumentException('non-nullable pluginId cannot be null');
        }
        $this->container['pluginId'] = $pluginId;

        return $this;
    }

    /**
     * Gets skill
     *
     * @return string|null
     */
    public function getSkill(): ?string
    {
        return $this->container['skill'];
    }

    /**
     * Sets skill
     *
     * @param string|null $skill The skill directory the trigger runs, absent when the trigger leaves the choice of skill to the investigation
     *
     * @return $this
     */
    public function setSkill(?string $skill): static
    {
        if (is_null($skill)) {
            throw new InvalidArgumentException('non-nullable skill cannot be null');
        }
        $this->container['skill'] = $skill;

        return $this;
    }

    /**
     * Gets taskSet
     *
     * @return string
     */
    public function getTaskSet(): string
    {
        return $this->container['taskSet'];
    }

    /**
     * Sets taskSet
     *
     * @param string $taskSet Whether the trigger hands the agent a task of its own (true, false)
     *
     * @return $this
     */
    public function setTaskSet(string $taskSet): static
    {
        if (is_null($taskSet)) {
            throw new InvalidArgumentException('non-nullable taskSet cannot be null');
        }
        $this->container['taskSet'] = $taskSet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


