<?php
/**
 * CatalogEntryReferenceV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * CatalogEntryReferenceV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CatalogEntryReferenceV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'CatalogEntryReferenceV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'archivedAt' => '\DateTime',
        'catalogEntryId' => 'string',
        'catalogEntryName' => 'string',
        'catalogTypeId' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'archivedAt' => 'date-time',
        'catalogEntryId' => null,
        'catalogEntryName' => null,
        'catalogTypeId' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'archivedAt' => false,
        'catalogEntryId' => false,
        'catalogEntryName' => false,
        'catalogTypeId' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'archivedAt' => 'archived_at',
        'catalogEntryId' => 'catalog_entry_id',
        'catalogEntryName' => 'catalog_entry_name',
        'catalogTypeId' => 'catalog_type_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'archivedAt' => 'setArchivedAt',
        'catalogEntryId' => 'setCatalogEntryId',
        'catalogEntryName' => 'setCatalogEntryName',
        'catalogTypeId' => 'setCatalogTypeId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'archivedAt' => 'getArchivedAt',
        'catalogEntryId' => 'getCatalogEntryId',
        'catalogEntryName' => 'getCatalogEntryName',
        'catalogTypeId' => 'getCatalogTypeId'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('archivedAt', $data ?? [], null);
        $this->setIfExists('catalogEntryId', $data ?? [], null);
        $this->setIfExists('catalogEntryName', $data ?? [], null);
        $this->setIfExists('catalogTypeId', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['catalogEntryId'] === null) {
            $invalidProperties[] = "'catalogEntryId' can't be null";
        }
        if ($this->container['catalogEntryName'] === null) {
            $invalidProperties[] = "'catalogEntryName' can't be null";
        }
        if ($this->container['catalogTypeId'] === null) {
            $invalidProperties[] = "'catalogTypeId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets archivedAt
     *
     * @return \DateTime|null
     */
    public function getArchivedAt(): ?\DateTime
    {
        return $this->container['archivedAt'];
    }

    /**
     * Sets archivedAt
     *
     * @param \DateTime|null $archivedAt When this entry was archived
     *
     * @return $this
     */
    public function setArchivedAt(?\DateTime $archivedAt): static
    {
        if (is_null($archivedAt)) {
            throw new InvalidArgumentException('non-nullable archivedAt cannot be null');
        }
        $this->container['archivedAt'] = $archivedAt;

        return $this;
    }

    /**
     * Gets catalogEntryId
     *
     * @return string
     */
    public function getCatalogEntryId(): string
    {
        return $this->container['catalogEntryId'];
    }

    /**
     * Sets catalogEntryId
     *
     * @param string $catalogEntryId ID of this catalog entry
     *
     * @return $this
     */
    public function setCatalogEntryId(string $catalogEntryId): static
    {
        if (is_null($catalogEntryId)) {
            throw new InvalidArgumentException('non-nullable catalogEntryId cannot be null');
        }
        $this->container['catalogEntryId'] = $catalogEntryId;

        return $this;
    }

    /**
     * Gets catalogEntryName
     *
     * @return string
     */
    public function getCatalogEntryName(): string
    {
        return $this->container['catalogEntryName'];
    }

    /**
     * Sets catalogEntryName
     *
     * @param string $catalogEntryName The name of this entry
     *
     * @return $this
     */
    public function setCatalogEntryName(string $catalogEntryName): static
    {
        if (is_null($catalogEntryName)) {
            throw new InvalidArgumentException('non-nullable catalogEntryName cannot be null');
        }
        $this->container['catalogEntryName'] = $catalogEntryName;

        return $this;
    }

    /**
     * Gets catalogTypeId
     *
     * @return string
     */
    public function getCatalogTypeId(): string
    {
        return $this->container['catalogTypeId'];
    }

    /**
     * Sets catalogTypeId
     *
     * @param string $catalogTypeId ID of this catalog type
     *
     * @return $this
     */
    public function setCatalogTypeId(string $catalogTypeId): static
    {
        if (is_null($catalogTypeId)) {
            throw new InvalidArgumentException('non-nullable catalogTypeId cannot be null');
        }
        $this->container['catalogTypeId'] = $catalogTypeId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


