<?php
/**
 * EscalationPathTemplateV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * EscalationPathTemplateV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EscalationPathTemplateV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'EscalationPathTemplateV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'description' => 'string',
        'expressions' => '\IncidentIo\Model\ExpressionV2[]',
        'hasHistoricalEscalationPathVersions' => 'bool',
        'id' => 'string',
        'name' => 'string',
        'params' => '\IncidentIo\Model\EngineParamV2[]',
        'path' => '\IncidentIo\Model\EscalationPathTemplateNodeV2[]',
        'repeatConfig' => '\IncidentIo\Model\EscalationPathRepeatConfigV2',
        'workingHours' => '\IncidentIo\Model\WeekdayIntervalConfigV2[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'description' => null,
        'expressions' => null,
        'hasHistoricalEscalationPathVersions' => null,
        'id' => null,
        'name' => null,
        'params' => null,
        'path' => null,
        'repeatConfig' => null,
        'workingHours' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'description' => false,
        'expressions' => false,
        'hasHistoricalEscalationPathVersions' => false,
        'id' => false,
        'name' => false,
        'params' => false,
        'path' => false,
        'repeatConfig' => false,
        'workingHours' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'description' => 'description',
        'expressions' => 'expressions',
        'hasHistoricalEscalationPathVersions' => 'has_historical_escalation_path_versions',
        'id' => 'id',
        'name' => 'name',
        'params' => 'params',
        'path' => 'path',
        'repeatConfig' => 'repeat_config',
        'workingHours' => 'working_hours'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'description' => 'setDescription',
        'expressions' => 'setExpressions',
        'hasHistoricalEscalationPathVersions' => 'setHasHistoricalEscalationPathVersions',
        'id' => 'setId',
        'name' => 'setName',
        'params' => 'setParams',
        'path' => 'setPath',
        'repeatConfig' => 'setRepeatConfig',
        'workingHours' => 'setWorkingHours'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'description' => 'getDescription',
        'expressions' => 'getExpressions',
        'hasHistoricalEscalationPathVersions' => 'getHasHistoricalEscalationPathVersions',
        'id' => 'getId',
        'name' => 'getName',
        'params' => 'getParams',
        'path' => 'getPath',
        'repeatConfig' => 'getRepeatConfig',
        'workingHours' => 'getWorkingHours'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('expressions', $data ?? [], null);
        $this->setIfExists('hasHistoricalEscalationPathVersions', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('params', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('repeatConfig', $data ?? [], null);
        $this->setIfExists('workingHours', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['expressions'] === null) {
            $invalidProperties[] = "'expressions' can't be null";
        }
        if ($this->container['hasHistoricalEscalationPathVersions'] === null) {
            $invalidProperties[] = "'hasHistoricalEscalationPathVersions' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['params'] === null) {
            $invalidProperties[] = "'params' can't be null";
        }
        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description A description of what this template is for.
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets expressions
     *
     * @return \IncidentIo\Model\ExpressionV2[]
     */
    public function getExpressions(): array
    {
        return $this->container['expressions'];
    }

    /**
     * Sets expressions
     *
     * @param \IncidentIo\Model\ExpressionV2[] $expressions Expressions backing the template's binding targets.
     *
     * @return $this
     */
    public function setExpressions(array $expressions): static
    {
        if (is_null($expressions)) {
            throw new InvalidArgumentException('non-nullable expressions cannot be null');
        }
        $this->container['expressions'] = $expressions;

        return $this;
    }

    /**
     * Gets hasHistoricalEscalationPathVersions
     *
     * @return bool
     */
    public function getHasHistoricalEscalationPathVersions(): bool
    {
        return $this->container['hasHistoricalEscalationPathVersions'];
    }

    /**
     * Sets hasHistoricalEscalationPathVersions
     *
     * @param bool $hasHistoricalEscalationPathVersions Whether a previous escalation path version uses this template. You cannot restore those versions after the template is archived.
     *
     * @return $this
     */
    public function setHasHistoricalEscalationPathVersions(bool $hasHistoricalEscalationPathVersions): static
    {
        if (is_null($hasHistoricalEscalationPathVersions)) {
            throw new InvalidArgumentException('non-nullable hasHistoricalEscalationPathVersions cannot be null');
        }
        $this->container['hasHistoricalEscalationPathVersions'] = $hasHistoricalEscalationPathVersions;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier for this template.
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of this template.
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets params
     *
     * @return \IncidentIo\Model\EngineParamV2[]
     */
    public function getParams(): array
    {
        return $this->container['params'];
    }

    /**
     * Sets params
     *
     * @param \IncidentIo\Model\EngineParamV2[] $params The parameters declared by this template.
     *
     * @return $this
     */
    public function setParams(array $params): static
    {
        if (is_null($params)) {
            throw new InvalidArgumentException('non-nullable params cannot be null');
        }
        $this->container['params'] = $params;

        return $this;
    }

    /**
     * Gets path
     *
     * @return \IncidentIo\Model\EscalationPathTemplateNodeV2[]
     */
    public function getPath(): array
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param \IncidentIo\Model\EscalationPathTemplateNodeV2[] $path The nodes that form the levels and branches of this template.
     *
     * @return $this
     */
    public function setPath(array $path): static
    {
        if (is_null($path)) {
            throw new InvalidArgumentException('non-nullable path cannot be null');
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets repeatConfig
     *
     * @return \IncidentIo\Model\EscalationPathRepeatConfigV2|null
     */
    public function getRepeatConfig(): ?\IncidentIo\Model\EscalationPathRepeatConfigV2
    {
        return $this->container['repeatConfig'];
    }

    /**
     * Sets repeatConfig
     *
     * @param \IncidentIo\Model\EscalationPathRepeatConfigV2|null $repeatConfig repeatConfig
     *
     * @return $this
     */
    public function setRepeatConfig(?\IncidentIo\Model\EscalationPathRepeatConfigV2 $repeatConfig): static
    {
        if (is_null($repeatConfig)) {
            throw new InvalidArgumentException('non-nullable repeatConfig cannot be null');
        }
        $this->container['repeatConfig'] = $repeatConfig;

        return $this;
    }

    /**
     * Gets workingHours
     *
     * @return \IncidentIo\Model\WeekdayIntervalConfigV2[]|null
     */
    public function getWorkingHours(): ?array
    {
        return $this->container['workingHours'];
    }

    /**
     * Sets workingHours
     *
     * @param \IncidentIo\Model\WeekdayIntervalConfigV2[]|null $workingHours The working hours for this template.
     *
     * @return $this
     */
    public function setWorkingHours(?array $workingHours): static
    {
        if (is_null($workingHours)) {
            throw new InvalidArgumentException('non-nullable workingHours cannot be null');
        }
        $this->container['workingHours'] = $workingHours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


