<?php
/**
 * EscalationV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * EscalationV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EscalationV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'EscalationV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'createdAt' => '\DateTime',
        'creator' => '\IncidentIo\Model\EscalationCreatorV2',
        'description' => 'string',
        'escalationPathId' => 'string',
        'events' => '\IncidentIo\Model\EscalationEventV2[]',
        'id' => 'string',
        'priority' => '\IncidentIo\Model\EscalationPriorityV2',
        'relatedAlerts' => '\IncidentIo\Model\AlertSlimV2[]',
        'relatedIncidents' => '\IncidentIo\Model\IncidentSlimV2[]',
        'status' => 'string',
        'title' => 'string',
        'updatedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'createdAt' => 'date-time',
        'creator' => null,
        'description' => null,
        'escalationPathId' => null,
        'events' => null,
        'id' => null,
        'priority' => null,
        'relatedAlerts' => null,
        'relatedIncidents' => null,
        'status' => null,
        'title' => null,
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'createdAt' => false,
        'creator' => false,
        'description' => false,
        'escalationPathId' => false,
        'events' => false,
        'id' => false,
        'priority' => false,
        'relatedAlerts' => false,
        'relatedIncidents' => false,
        'status' => false,
        'title' => false,
        'updatedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'createdAt' => 'created_at',
        'creator' => 'creator',
        'description' => 'description',
        'escalationPathId' => 'escalation_path_id',
        'events' => 'events',
        'id' => 'id',
        'priority' => 'priority',
        'relatedAlerts' => 'related_alerts',
        'relatedIncidents' => 'related_incidents',
        'status' => 'status',
        'title' => 'title',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'createdAt' => 'setCreatedAt',
        'creator' => 'setCreator',
        'description' => 'setDescription',
        'escalationPathId' => 'setEscalationPathId',
        'events' => 'setEvents',
        'id' => 'setId',
        'priority' => 'setPriority',
        'relatedAlerts' => 'setRelatedAlerts',
        'relatedIncidents' => 'setRelatedIncidents',
        'status' => 'setStatus',
        'title' => 'setTitle',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'createdAt' => 'getCreatedAt',
        'creator' => 'getCreator',
        'description' => 'getDescription',
        'escalationPathId' => 'getEscalationPathId',
        'events' => 'getEvents',
        'id' => 'getId',
        'priority' => 'getPriority',
        'relatedAlerts' => 'getRelatedAlerts',
        'relatedIncidents' => 'getRelatedIncidents',
        'status' => 'getStatus',
        'title' => 'getTitle',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const STATUS_PENDING = 'pending';
    public const STATUS_TRIGGERED = 'triggered';
    public const STATUS_ACKED = 'acked';
    public const STATUS_RESOLVED = 'resolved';
    public const STATUS_EXPIRED = 'expired';
    public const STATUS_CANCELLED = 'cancelled';
    public const STATUS_SNOOZED = 'snoozed';
    public const STATUS_DELAYED = 'delayed';
    public const STATUS_PENDING_REPEAT = 'pending_repeat';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING,
            self::STATUS_TRIGGERED,
            self::STATUS_ACKED,
            self::STATUS_RESOLVED,
            self::STATUS_EXPIRED,
            self::STATUS_CANCELLED,
            self::STATUS_SNOOZED,
            self::STATUS_DELAYED,
            self::STATUS_PENDING_REPEAT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('escalationPathId', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('relatedAlerts', $data ?? [], null);
        $this->setIfExists('relatedIncidents', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['creator'] === null) {
            $invalidProperties[] = "'creator' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['events'] === null) {
            $invalidProperties[] = "'events' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['priority'] === null) {
            $invalidProperties[] = "'priority' can't be null";
        }
        if ($this->container['relatedAlerts'] === null) {
            $invalidProperties[] = "'relatedAlerts' can't be null";
        }
        if ($this->container['relatedIncidents'] === null) {
            $invalidProperties[] = "'relatedIncidents' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt When this escalation was created
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return \IncidentIo\Model\EscalationCreatorV2
     */
    public function getCreator(): \IncidentIo\Model\EscalationCreatorV2
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param \IncidentIo\Model\EscalationCreatorV2 $creator creator
     *
     * @return $this
     */
    public function setCreator(\IncidentIo\Model\EscalationCreatorV2 $creator): static
    {
        if (is_null($creator)) {
            throw new InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Additional detail provided with this escalation. When it isn't set explicitly, this is taken from the alert description or the incident summary, and is empty when neither applies.
     *
     * @return $this
     */
    public function setDescription(string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets escalationPathId
     *
     * @return string|null
     */
    public function getEscalationPathId(): ?string
    {
        return $this->container['escalationPathId'];
    }

    /**
     * Sets escalationPathId
     *
     * @param string|null $escalationPathId Unique identifier of the escalation path that the escalation was created from
     *
     * @return $this
     */
    public function setEscalationPathId(?string $escalationPathId): static
    {
        if (is_null($escalationPathId)) {
            throw new InvalidArgumentException('non-nullable escalationPathId cannot be null');
        }
        $this->container['escalationPathId'] = $escalationPathId;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \IncidentIo\Model\EscalationEventV2[]
     */
    public function getEvents(): array
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \IncidentIo\Model\EscalationEventV2[] $events Events which describe the history of this escalation. Events include information about what users or channels were notified and what users acked.
     *
     * @return $this
     */
    public function setEvents(array $events): static
    {
        if (is_null($events)) {
            throw new InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique ID of the escalation
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return \IncidentIo\Model\EscalationPriorityV2
     */
    public function getPriority(): \IncidentIo\Model\EscalationPriorityV2
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param \IncidentIo\Model\EscalationPriorityV2 $priority priority
     *
     * @return $this
     */
    public function setPriority(\IncidentIo\Model\EscalationPriorityV2 $priority): static
    {
        if (is_null($priority)) {
            throw new InvalidArgumentException('non-nullable priority cannot be null');
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets relatedAlerts
     *
     * @return \IncidentIo\Model\AlertSlimV2[]
     */
    public function getRelatedAlerts(): array
    {
        return $this->container['relatedAlerts'];
    }

    /**
     * Sets relatedAlerts
     *
     * @param \IncidentIo\Model\AlertSlimV2[] $relatedAlerts Alerts related to this escalation
     *
     * @return $this
     */
    public function setRelatedAlerts(array $relatedAlerts): static
    {
        if (is_null($relatedAlerts)) {
            throw new InvalidArgumentException('non-nullable relatedAlerts cannot be null');
        }
        $this->container['relatedAlerts'] = $relatedAlerts;

        return $this;
    }

    /**
     * Gets relatedIncidents
     *
     * @return \IncidentIo\Model\IncidentSlimV2[]
     */
    public function getRelatedIncidents(): array
    {
        return $this->container['relatedIncidents'];
    }

    /**
     * Sets relatedIncidents
     *
     * @param \IncidentIo\Model\IncidentSlimV2[] $relatedIncidents Incidents related to this escalation
     *
     * @return $this
     */
    public function setRelatedIncidents(array $relatedIncidents): static
    {
        if (is_null($relatedIncidents)) {
            throw new InvalidArgumentException('non-nullable relatedIncidents cannot be null');
        }
        $this->container['relatedIncidents'] = $relatedIncidents;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus(): string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Status of the escalation
     *
     * @return $this
     */
    public function setStatus(string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle(): string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of this escalation
     *
     * @return $this
     */
    public function setTitle(string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt When this escalation was last updated
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


