<?php
/**
 * ExpressionOperationPayloadV3
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * ExpressionOperationPayloadV3 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ExpressionOperationPayloadV3 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ExpressionOperationPayloadV3';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'branches' => '\IncidentIo\Model\ExpressionBranchesOptsPayloadV3',
        'cast' => '\IncidentIo\Model\ExpressionCastOptsPayloadV3',
        'concatenate' => '\IncidentIo\Model\ExpressionConcatenateOptsPayloadV3',
        'filter' => '\IncidentIo\Model\ExpressionFilterOptsPayloadV3',
        'navigate' => '\IncidentIo\Model\ExpressionNavigateOptsPayloadV3',
        'operationType' => 'string',
        'parse' => '\IncidentIo\Model\ExpressionParseOptsPayloadV3'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'branches' => null,
        'cast' => null,
        'concatenate' => null,
        'filter' => null,
        'navigate' => null,
        'operationType' => null,
        'parse' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'branches' => false,
        'cast' => false,
        'concatenate' => false,
        'filter' => false,
        'navigate' => false,
        'operationType' => false,
        'parse' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'branches' => 'branches',
        'cast' => 'cast',
        'concatenate' => 'concatenate',
        'filter' => 'filter',
        'navigate' => 'navigate',
        'operationType' => 'operation_type',
        'parse' => 'parse'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'branches' => 'setBranches',
        'cast' => 'setCast',
        'concatenate' => 'setConcatenate',
        'filter' => 'setFilter',
        'navigate' => 'setNavigate',
        'operationType' => 'setOperationType',
        'parse' => 'setParse'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'branches' => 'getBranches',
        'cast' => 'getCast',
        'concatenate' => 'getConcatenate',
        'filter' => 'getFilter',
        'navigate' => 'getNavigate',
        'operationType' => 'getOperationType',
        'parse' => 'getParse'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const OPERATION_TYPE_NAVIGATE = 'navigate';
    public const OPERATION_TYPE_FILTER = 'filter';
    public const OPERATION_TYPE_CONCATENATE = 'concatenate';
    public const OPERATION_TYPE_COUNT = 'count';
    public const OPERATION_TYPE_MIN = 'min';
    public const OPERATION_TYPE_MAX = 'max';
    public const OPERATION_TYPE_SUM = 'sum';
    public const OPERATION_TYPE_RANDOM = 'random';
    public const OPERATION_TYPE_FIRST = 'first';
    public const OPERATION_TYPE_PARSE = 'parse';
    public const OPERATION_TYPE_BRANCHES = 'branches';
    public const OPERATION_TYPE_CAST = 'cast';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getOperationTypeAllowableValues()
    {
        return [
            self::OPERATION_TYPE_NAVIGATE,
            self::OPERATION_TYPE_FILTER,
            self::OPERATION_TYPE_CONCATENATE,
            self::OPERATION_TYPE_COUNT,
            self::OPERATION_TYPE_MIN,
            self::OPERATION_TYPE_MAX,
            self::OPERATION_TYPE_SUM,
            self::OPERATION_TYPE_RANDOM,
            self::OPERATION_TYPE_FIRST,
            self::OPERATION_TYPE_PARSE,
            self::OPERATION_TYPE_BRANCHES,
            self::OPERATION_TYPE_CAST,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('branches', $data ?? [], null);
        $this->setIfExists('cast', $data ?? [], null);
        $this->setIfExists('concatenate', $data ?? [], null);
        $this->setIfExists('filter', $data ?? [], null);
        $this->setIfExists('navigate', $data ?? [], null);
        $this->setIfExists('operationType', $data ?? [], null);
        $this->setIfExists('parse', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['operationType'] === null) {
            $invalidProperties[] = "'operationType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets branches
     *
     * @return \IncidentIo\Model\ExpressionBranchesOptsPayloadV3|null
     */
    public function getBranches(): ?\IncidentIo\Model\ExpressionBranchesOptsPayloadV3
    {
        return $this->container['branches'];
    }

    /**
     * Sets branches
     *
     * @param \IncidentIo\Model\ExpressionBranchesOptsPayloadV3|null $branches branches
     *
     * @return $this
     */
    public function setBranches(?\IncidentIo\Model\ExpressionBranchesOptsPayloadV3 $branches): static
    {
        if (is_null($branches)) {
            throw new InvalidArgumentException('non-nullable branches cannot be null');
        }
        $this->container['branches'] = $branches;

        return $this;
    }

    /**
     * Gets cast
     *
     * @return \IncidentIo\Model\ExpressionCastOptsPayloadV3|null
     */
    public function getCast(): ?\IncidentIo\Model\ExpressionCastOptsPayloadV3
    {
        return $this->container['cast'];
    }

    /**
     * Sets cast
     *
     * @param \IncidentIo\Model\ExpressionCastOptsPayloadV3|null $cast cast
     *
     * @return $this
     */
    public function setCast(?\IncidentIo\Model\ExpressionCastOptsPayloadV3 $cast): static
    {
        if (is_null($cast)) {
            throw new InvalidArgumentException('non-nullable cast cannot be null');
        }
        $this->container['cast'] = $cast;

        return $this;
    }

    /**
     * Gets concatenate
     *
     * @return \IncidentIo\Model\ExpressionConcatenateOptsPayloadV3|null
     */
    public function getConcatenate(): ?\IncidentIo\Model\ExpressionConcatenateOptsPayloadV3
    {
        return $this->container['concatenate'];
    }

    /**
     * Sets concatenate
     *
     * @param \IncidentIo\Model\ExpressionConcatenateOptsPayloadV3|null $concatenate concatenate
     *
     * @return $this
     */
    public function setConcatenate(?\IncidentIo\Model\ExpressionConcatenateOptsPayloadV3 $concatenate): static
    {
        if (is_null($concatenate)) {
            throw new InvalidArgumentException('non-nullable concatenate cannot be null');
        }
        $this->container['concatenate'] = $concatenate;

        return $this;
    }

    /**
     * Gets filter
     *
     * @return \IncidentIo\Model\ExpressionFilterOptsPayloadV3|null
     */
    public function getFilter(): ?\IncidentIo\Model\ExpressionFilterOptsPayloadV3
    {
        return $this->container['filter'];
    }

    /**
     * Sets filter
     *
     * @param \IncidentIo\Model\ExpressionFilterOptsPayloadV3|null $filter filter
     *
     * @return $this
     */
    public function setFilter(?\IncidentIo\Model\ExpressionFilterOptsPayloadV3 $filter): static
    {
        if (is_null($filter)) {
            throw new InvalidArgumentException('non-nullable filter cannot be null');
        }
        $this->container['filter'] = $filter;

        return $this;
    }

    /**
     * Gets navigate
     *
     * @return \IncidentIo\Model\ExpressionNavigateOptsPayloadV3|null
     */
    public function getNavigate(): ?\IncidentIo\Model\ExpressionNavigateOptsPayloadV3
    {
        return $this->container['navigate'];
    }

    /**
     * Sets navigate
     *
     * @param \IncidentIo\Model\ExpressionNavigateOptsPayloadV3|null $navigate navigate
     *
     * @return $this
     */
    public function setNavigate(?\IncidentIo\Model\ExpressionNavigateOptsPayloadV3 $navigate): static
    {
        if (is_null($navigate)) {
            throw new InvalidArgumentException('non-nullable navigate cannot be null');
        }
        $this->container['navigate'] = $navigate;

        return $this;
    }

    /**
     * Gets operationType
     *
     * @return string
     */
    public function getOperationType(): string
    {
        return $this->container['operationType'];
    }

    /**
     * Sets operationType
     *
     * @param string $operationType The type of the operation
     *
     * @return $this
     */
    public function setOperationType(string $operationType): static
    {
        if (is_null($operationType)) {
            throw new InvalidArgumentException('non-nullable operationType cannot be null');
        }
        $this->container['operationType'] = $operationType;

        return $this;
    }

    /**
     * Gets parse
     *
     * @return \IncidentIo\Model\ExpressionParseOptsPayloadV3|null
     */
    public function getParse(): ?\IncidentIo\Model\ExpressionParseOptsPayloadV3
    {
        return $this->container['parse'];
    }

    /**
     * Sets parse
     *
     * @param \IncidentIo\Model\ExpressionParseOptsPayloadV3|null $parse parse
     *
     * @return $this
     */
    public function setParse(?\IncidentIo\Model\ExpressionParseOptsPayloadV3 $parse): static
    {
        if (is_null($parse)) {
            throw new InvalidArgumentException('non-nullable parse cannot be null');
        }
        $this->container['parse'] = $parse;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


