<?php
/**
 * IncidentFormsUpdatePayloadV3
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * IncidentFormsUpdatePayloadV3 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class IncidentFormsUpdatePayloadV3 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'IncidentFormsUpdatePayloadV3';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'expressions' => '\IncidentIo\Model\ExpressionPayloadV3[]',
        'formType' => 'string',
        'incidentTypeId' => 'string',
        'lifecycleElements' => '\IncidentIo\Model\IncidentFormLifecycleElementPayloadV3[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'expressions' => null,
        'formType' => null,
        'incidentTypeId' => null,
        'lifecycleElements' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'expressions' => false,
        'formType' => false,
        'incidentTypeId' => false,
        'lifecycleElements' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'expressions' => 'expressions',
        'formType' => 'form_type',
        'incidentTypeId' => 'incident_type_id',
        'lifecycleElements' => 'lifecycle_elements'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'expressions' => 'setExpressions',
        'formType' => 'setFormType',
        'incidentTypeId' => 'setIncidentTypeId',
        'lifecycleElements' => 'setLifecycleElements'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'expressions' => 'getExpressions',
        'formType' => 'getFormType',
        'incidentTypeId' => 'getIncidentTypeId',
        'lifecycleElements' => 'getLifecycleElements'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const FORM_TYPE__DECLARE = 'declare';
    public const FORM_TYPE_ACCEPT = 'accept';
    public const FORM_TYPE_UPDATE = 'update';
    public const FORM_TYPE_RESOLVE = 'resolve';
    public const FORM_TYPE_RETROSPECTIVE = 'retrospective';
    public const FORM_TYPE_CUSTOM_FIELDS = 'custom-fields';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getFormTypeAllowableValues()
    {
        return [
            self::FORM_TYPE__DECLARE,
            self::FORM_TYPE_ACCEPT,
            self::FORM_TYPE_UPDATE,
            self::FORM_TYPE_RESOLVE,
            self::FORM_TYPE_RETROSPECTIVE,
            self::FORM_TYPE_CUSTOM_FIELDS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('expressions', $data ?? [], null);
        $this->setIfExists('formType', $data ?? [], null);
        $this->setIfExists('incidentTypeId', $data ?? [], null);
        $this->setIfExists('lifecycleElements', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['expressions'] === null) {
            $invalidProperties[] = "'expressions' can't be null";
        }
        if ($this->container['formType'] === null) {
            $invalidProperties[] = "'formType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets expressions
     *
     * @return \IncidentIo\Model\ExpressionPayloadV3[]
     */
    public function getExpressions(): array
    {
        return $this->container['expressions'];
    }

    /**
     * Sets expressions
     *
     * @param \IncidentIo\Model\ExpressionPayloadV3[] $expressions Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
     *
     * @return $this
     */
    public function setExpressions(array $expressions): static
    {
        if (is_null($expressions)) {
            throw new InvalidArgumentException('non-nullable expressions cannot be null');
        }
        $this->container['expressions'] = $expressions;

        return $this;
    }

    /**
     * Gets formType
     *
     * @return string
     */
    public function getFormType(): string
    {
        return $this->container['formType'];
    }

    /**
     * Sets formType
     *
     * @param string $formType Which form this is. Escalate forms are not part of this API.
     *
     * @return $this
     */
    public function setFormType(string $formType): static
    {
        if (is_null($formType)) {
            throw new InvalidArgumentException('non-nullable formType cannot be null');
        }
        $this->container['formType'] = $formType;

        return $this;
    }

    /**
     * Gets incidentTypeId
     *
     * @return string|null
     */
    public function getIncidentTypeId(): ?string
    {
        return $this->container['incidentTypeId'];
    }

    /**
     * Sets incidentTypeId
     *
     * @param string|null $incidentTypeId The incident type this form belongs to. Leave unset for the organisation's default form of this type.
     *
     * @return $this
     */
    public function setIncidentTypeId(?string $incidentTypeId): static
    {
        if (is_null($incidentTypeId)) {
            throw new InvalidArgumentException('non-nullable incidentTypeId cannot be null');
        }
        $this->container['incidentTypeId'] = $incidentTypeId;

        return $this;
    }

    /**
     * Gets lifecycleElements
     *
     * @return \IncidentIo\Model\IncidentFormLifecycleElementPayloadV3[]|null
     */
    public function getLifecycleElements(): ?array
    {
        return $this->container['lifecycleElements'];
    }

    /**
     * Sets lifecycleElements
     *
     * @param \IncidentIo\Model\IncidentFormLifecycleElementPayloadV3[]|null $lifecycleElements Elements on this form, in display order. List position is the order: there is no separate rank.
     *
     * @return $this
     */
    public function setLifecycleElements(?array $lifecycleElements): static
    {
        if (is_null($lifecycleElements)) {
            throw new InvalidArgumentException('non-nullable lifecycleElements cannot be null');
        }
        $this->container['lifecycleElements'] = $lifecycleElements;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


