<?php
/**
 * PayReportV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * PayReportV2 Class Doc Comment
 *
 * @description A pay report values the time a set of users spent on-call over a date window, using the rates from a pay config.  This is a summary: the headline totals, and the parameters the report was generated with. The shifts behind those totals, and the per-user and per-schedule breakdowns, come from downloading the report as CSV.  Reports are immutable snapshots: once generated, changing the pay config or the schedules behind it will not change the report. Generate a new one instead.  A report starts as a draft and becomes visible to everyone in your organisation when you publish it.  Reports are generated in the background, so a report you have just asked for has no totals yet. Its status says whether they are still coming, and a report that failed carries the reason it will never have them.
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PayReportV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'PayReportV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'createdAt' => '\DateTime',
        'creator' => '\IncidentIo\Model\ActorV2',
        'endDate' => 'string',
        'errorCode' => 'string',
        'errorMessage' => 'string',
        'id' => 'string',
        'name' => 'string',
        'overlappingShifts' => 'string',
        'publishedAt' => '\DateTime',
        'scheduleIds' => 'string[]',
        'startDate' => 'string',
        'status' => 'string',
        'totalDurationSeconds' => 'int',
        'totalPayByCurrency' => 'array<string,int>',
        'unpaidShifts' => 'string',
        'updatedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'createdAt' => 'date-time',
        'creator' => null,
        'endDate' => null,
        'errorCode' => null,
        'errorMessage' => null,
        'id' => null,
        'name' => null,
        'overlappingShifts' => null,
        'publishedAt' => 'date-time',
        'scheduleIds' => null,
        'startDate' => null,
        'status' => null,
        'totalDurationSeconds' => 'int64',
        'totalPayByCurrency' => 'int64',
        'unpaidShifts' => null,
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'createdAt' => false,
        'creator' => false,
        'endDate' => false,
        'errorCode' => false,
        'errorMessage' => false,
        'id' => false,
        'name' => false,
        'overlappingShifts' => false,
        'publishedAt' => false,
        'scheduleIds' => false,
        'startDate' => false,
        'status' => false,
        'totalDurationSeconds' => false,
        'totalPayByCurrency' => false,
        'unpaidShifts' => false,
        'updatedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'createdAt' => 'created_at',
        'creator' => 'creator',
        'endDate' => 'end_date',
        'errorCode' => 'error_code',
        'errorMessage' => 'error_message',
        'id' => 'id',
        'name' => 'name',
        'overlappingShifts' => 'overlapping_shifts',
        'publishedAt' => 'published_at',
        'scheduleIds' => 'schedule_ids',
        'startDate' => 'start_date',
        'status' => 'status',
        'totalDurationSeconds' => 'total_duration_seconds',
        'totalPayByCurrency' => 'total_pay_by_currency',
        'unpaidShifts' => 'unpaid_shifts',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'createdAt' => 'setCreatedAt',
        'creator' => 'setCreator',
        'endDate' => 'setEndDate',
        'errorCode' => 'setErrorCode',
        'errorMessage' => 'setErrorMessage',
        'id' => 'setId',
        'name' => 'setName',
        'overlappingShifts' => 'setOverlappingShifts',
        'publishedAt' => 'setPublishedAt',
        'scheduleIds' => 'setScheduleIds',
        'startDate' => 'setStartDate',
        'status' => 'setStatus',
        'totalDurationSeconds' => 'setTotalDurationSeconds',
        'totalPayByCurrency' => 'setTotalPayByCurrency',
        'unpaidShifts' => 'setUnpaidShifts',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'createdAt' => 'getCreatedAt',
        'creator' => 'getCreator',
        'endDate' => 'getEndDate',
        'errorCode' => 'getErrorCode',
        'errorMessage' => 'getErrorMessage',
        'id' => 'getId',
        'name' => 'getName',
        'overlappingShifts' => 'getOverlappingShifts',
        'publishedAt' => 'getPublishedAt',
        'scheduleIds' => 'getScheduleIds',
        'startDate' => 'getStartDate',
        'status' => 'getStatus',
        'totalDurationSeconds' => 'getTotalDurationSeconds',
        'totalPayByCurrency' => 'getTotalPayByCurrency',
        'unpaidShifts' => 'getUnpaidShifts',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const ERROR_CODE_INVALID_REQUEST = 'invalid_request';
    public const ERROR_CODE_TIMED_OUT = 'timed_out';
    public const OVERLAPPING_SHIFTS_PAID_ONCE = 'paid_once';
    public const OVERLAPPING_SHIFTS_PAID_PER_SCHEDULE = 'paid_per_schedule';
    public const STATUS_PENDING = 'pending';
    public const STATUS_GENERATING = 'generating';
    public const STATUS_COMPLETE = 'complete';
    public const STATUS_FAILED = 'failed';
    public const UNPAID_SHIFTS_INCLUDED = 'included';
    public const UNPAID_SHIFTS_EXCLUDED = 'excluded';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getErrorCodeAllowableValues()
    {
        return [
            self::ERROR_CODE_INVALID_REQUEST,
            self::ERROR_CODE_TIMED_OUT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getOverlappingShiftsAllowableValues()
    {
        return [
            self::OVERLAPPING_SHIFTS_PAID_ONCE,
            self::OVERLAPPING_SHIFTS_PAID_PER_SCHEDULE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING,
            self::STATUS_GENERATING,
            self::STATUS_COMPLETE,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getUnpaidShiftsAllowableValues()
    {
        return [
            self::UNPAID_SHIFTS_INCLUDED,
            self::UNPAID_SHIFTS_EXCLUDED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('endDate', $data ?? [], null);
        $this->setIfExists('errorCode', $data ?? [], null);
        $this->setIfExists('errorMessage', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('overlappingShifts', $data ?? [], null);
        $this->setIfExists('publishedAt', $data ?? [], null);
        $this->setIfExists('scheduleIds', $data ?? [], null);
        $this->setIfExists('startDate', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('totalDurationSeconds', $data ?? [], null);
        $this->setIfExists('totalPayByCurrency', $data ?? [], null);
        $this->setIfExists('unpaidShifts', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['endDate'] === null) {
            $invalidProperties[] = "'endDate' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['overlappingShifts'] === null) {
            $invalidProperties[] = "'overlappingShifts' can't be null";
        }
        if ($this->container['scheduleIds'] === null) {
            $invalidProperties[] = "'scheduleIds' can't be null";
        }
        if ($this->container['startDate'] === null) {
            $invalidProperties[] = "'startDate' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['unpaidShifts'] === null) {
            $invalidProperties[] = "'unpaidShifts' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt When this report was created
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return \IncidentIo\Model\ActorV2|null
     */
    public function getCreator(): ?\IncidentIo\Model\ActorV2
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param \IncidentIo\Model\ActorV2|null $creator creator
     *
     * @return $this
     */
    public function setCreator(?\IncidentIo\Model\ActorV2 $creator): static
    {
        if (is_null($creator)) {
            throw new InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets endDate
     *
     * @return string
     */
    public function getEndDate(): string
    {
        return $this->container['endDate'];
    }

    /**
     * Sets endDate
     *
     * @param string $endDate Last date (YYYY-MM-DD) this report includes shifts from, inclusive
     *
     * @return $this
     */
    public function setEndDate(string $endDate): static
    {
        if (is_null($endDate)) {
            throw new InvalidArgumentException('non-nullable endDate cannot be null');
        }
        $this->container['endDate'] = $endDate;

        return $this;
    }

    /**
     * Gets errorCode
     *
     * @return string|null
     */
    public function getErrorCode(): ?string
    {
        return $this->container['errorCode'];
    }

    /**
     * Sets errorCode
     *
     * @param string|null $errorCode Why a report could not be generated
     *
     * @return $this
     */
    public function setErrorCode(?string $errorCode): static
    {
        if (is_null($errorCode)) {
            throw new InvalidArgumentException('non-nullable errorCode cannot be null');
        }
        $this->container['errorCode'] = $errorCode;

        return $this;
    }

    /**
     * Gets errorMessage
     *
     * @return string|null
     */
    public function getErrorMessage(): ?string
    {
        return $this->container['errorMessage'];
    }

    /**
     * Sets errorMessage
     *
     * @param string|null $errorMessage What went wrong, written for whoever asked for the report. Only set on a failed report.
     *
     * @return $this
     */
    public function setErrorMessage(?string $errorMessage): static
    {
        if (is_null($errorMessage)) {
            throw new InvalidArgumentException('non-nullable errorMessage cannot be null');
        }
        $this->container['errorMessage'] = $errorMessage;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier for this pay report
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human readable name for this report
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets overlappingShifts
     *
     * @return string
     */
    public function getOverlappingShifts(): string
    {
        return $this->container['overlappingShifts'];
    }

    /**
     * Sets overlappingShifts
     *
     * @param string $overlappingShifts How time spent on more than one schedule at once was paid
     *
     * @return $this
     */
    public function setOverlappingShifts(string $overlappingShifts): static
    {
        if (is_null($overlappingShifts)) {
            throw new InvalidArgumentException('non-nullable overlappingShifts cannot be null');
        }
        $this->container['overlappingShifts'] = $overlappingShifts;

        return $this;
    }

    /**
     * Gets publishedAt
     *
     * @return \DateTime|null
     */
    public function getPublishedAt(): ?\DateTime
    {
        return $this->container['publishedAt'];
    }

    /**
     * Sets publishedAt
     *
     * @param \DateTime|null $publishedAt When this report was published. Unset while the report is still a draft.
     *
     * @return $this
     */
    public function setPublishedAt(?\DateTime $publishedAt): static
    {
        if (is_null($publishedAt)) {
            throw new InvalidArgumentException('non-nullable publishedAt cannot be null');
        }
        $this->container['publishedAt'] = $publishedAt;

        return $this;
    }

    /**
     * Gets scheduleIds
     *
     * @return string[]
     */
    public function getScheduleIds(): array
    {
        return $this->container['scheduleIds'];
    }

    /**
     * Sets scheduleIds
     *
     * @param string[] $scheduleIds The schedules this report covers
     *
     * @return $this
     */
    public function setScheduleIds(array $scheduleIds): static
    {
        if (is_null($scheduleIds)) {
            throw new InvalidArgumentException('non-nullable scheduleIds cannot be null');
        }
        $this->container['scheduleIds'] = $scheduleIds;

        return $this;
    }

    /**
     * Gets startDate
     *
     * @return string
     */
    public function getStartDate(): string
    {
        return $this->container['startDate'];
    }

    /**
     * Sets startDate
     *
     * @param string $startDate First date (YYYY-MM-DD) this report includes shifts from, inclusive
     *
     * @return $this
     */
    public function setStartDate(string $startDate): static
    {
        if (is_null($startDate)) {
            throw new InvalidArgumentException('non-nullable startDate cannot be null');
        }
        $this->container['startDate'] = $startDate;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus(): string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status How far a report has got through being generated
     *
     * @return $this
     */
    public function setStatus(string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets totalDurationSeconds
     *
     * @return int|null
     */
    public function getTotalDurationSeconds(): ?int
    {
        return $this->container['totalDurationSeconds'];
    }

    /**
     * Sets totalDurationSeconds
     *
     * @param int|null $totalDurationSeconds Total time spent on-call across every shift in this report, in seconds. Unset until the report is complete, and for a legacy report, which we do not summarise.
     *
     * @return $this
     */
    public function setTotalDurationSeconds(?int $totalDurationSeconds): static
    {
        if (is_null($totalDurationSeconds)) {
            throw new InvalidArgumentException('non-nullable totalDurationSeconds cannot be null');
        }
        $this->container['totalDurationSeconds'] = $totalDurationSeconds;

        return $this;
    }

    /**
     * Gets totalPayByCurrency
     *
     * @return array<string,int>|null
     */
    public function getTotalPayByCurrency(): ?array
    {
        return $this->container['totalPayByCurrency'];
    }

    /**
     * Sets totalPayByCurrency
     *
     * @param array<string,int>|null $totalPayByCurrency Total owed for this report, keyed by ISO 4217 currency code, in the lowest denomination of that currency. Reports spanning pay configs with different currencies have an entry per currency, and those totals must not be summed. Unset until the report is complete, and for a legacy report, which we do not summarise.
     *
     * @return $this
     */
    public function setTotalPayByCurrency(?array $totalPayByCurrency): static
    {
        if (is_null($totalPayByCurrency)) {
            throw new InvalidArgumentException('non-nullable totalPayByCurrency cannot be null');
        }
        $this->container['totalPayByCurrency'] = $totalPayByCurrency;

        return $this;
    }

    /**
     * Gets unpaidShifts
     *
     * @return string
     */
    public function getUnpaidShifts(): string
    {
        return $this->container['unpaidShifts'];
    }

    /**
     * Sets unpaidShifts
     *
     * @param string $unpaidShifts Whether shifts that priced to zero are part of the report
     *
     * @return $this
     */
    public function setUnpaidShifts(string $unpaidShifts): static
    {
        if (is_null($unpaidShifts)) {
            throw new InvalidArgumentException('non-nullable unpaidShifts cannot be null');
        }
        $this->container['unpaidShifts'] = $unpaidShifts;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt When this report was last updated
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


