<?php
/**
 * PoliciesCreatePayloadV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * PoliciesCreatePayloadV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PoliciesCreatePayloadV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'PoliciesCreatePayloadV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'assignmentRules' => '\IncidentIo\Model\PolicyAssignmentRulesPayloadV2',
        'conditions' => '\IncidentIo\Model\ConditionGroupPayloadV2[]',
        'debrief' => '\IncidentIo\Model\PolicyDebriefPayloadV2',
        'description' => 'string',
        'expressions' => '\IncidentIo\Model\ExpressionPayloadV2[]',
        'followUp' => '\IncidentIo\Model\PolicyFollowUpPayloadV2',
        'name' => 'string',
        'onCallReadiness' => '\IncidentIo\Model\PolicyOnCallReadinessV2',
        'policyType' => 'string',
        'postMortem' => '\IncidentIo\Model\PolicyPostMortemPayloadV2',
        'schedule' => '\IncidentIo\Model\PolicyScheduleV2',
        'status' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'assignmentRules' => null,
        'conditions' => null,
        'debrief' => null,
        'description' => null,
        'expressions' => null,
        'followUp' => null,
        'name' => null,
        'onCallReadiness' => null,
        'policyType' => null,
        'postMortem' => null,
        'schedule' => null,
        'status' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'assignmentRules' => false,
        'conditions' => false,
        'debrief' => false,
        'description' => false,
        'expressions' => false,
        'followUp' => false,
        'name' => false,
        'onCallReadiness' => false,
        'policyType' => false,
        'postMortem' => false,
        'schedule' => false,
        'status' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'assignmentRules' => 'assignment_rules',
        'conditions' => 'conditions',
        'debrief' => 'debrief',
        'description' => 'description',
        'expressions' => 'expressions',
        'followUp' => 'follow_up',
        'name' => 'name',
        'onCallReadiness' => 'on_call_readiness',
        'policyType' => 'policy_type',
        'postMortem' => 'post_mortem',
        'schedule' => 'schedule',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'assignmentRules' => 'setAssignmentRules',
        'conditions' => 'setConditions',
        'debrief' => 'setDebrief',
        'description' => 'setDescription',
        'expressions' => 'setExpressions',
        'followUp' => 'setFollowUp',
        'name' => 'setName',
        'onCallReadiness' => 'setOnCallReadiness',
        'policyType' => 'setPolicyType',
        'postMortem' => 'setPostMortem',
        'schedule' => 'setSchedule',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'assignmentRules' => 'getAssignmentRules',
        'conditions' => 'getConditions',
        'debrief' => 'getDebrief',
        'description' => 'getDescription',
        'expressions' => 'getExpressions',
        'followUp' => 'getFollowUp',
        'name' => 'getName',
        'onCallReadiness' => 'getOnCallReadiness',
        'policyType' => 'getPolicyType',
        'postMortem' => 'getPostMortem',
        'schedule' => 'getSchedule',
        'status' => 'getStatus'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const POLICY_TYPE_DEBRIEF = 'debrief';
    public const POLICY_TYPE_FOLLOW_UP = 'follow_up';
    public const POLICY_TYPE_ON_CALL_READINESS = 'on_call_readiness';
    public const POLICY_TYPE_POST_MORTEM = 'post_mortem';
    public const POLICY_TYPE_SCHEDULE = 'schedule';
    public const POLICY_TYPE_SHIFT_CONFLICT = 'shift_conflict';
    public const POLICY_TYPE_VACATION_CONFLICT = 'vacation_conflict';
    public const STATUS_ENABLED = 'enabled';
    public const STATUS_DISABLED = 'disabled';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getPolicyTypeAllowableValues()
    {
        return [
            self::POLICY_TYPE_DEBRIEF,
            self::POLICY_TYPE_FOLLOW_UP,
            self::POLICY_TYPE_ON_CALL_READINESS,
            self::POLICY_TYPE_POST_MORTEM,
            self::POLICY_TYPE_SCHEDULE,
            self::POLICY_TYPE_SHIFT_CONFLICT,
            self::POLICY_TYPE_VACATION_CONFLICT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_ENABLED,
            self::STATUS_DISABLED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('assignmentRules', $data ?? [], null);
        $this->setIfExists('conditions', $data ?? [], null);
        $this->setIfExists('debrief', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('expressions', $data ?? [], null);
        $this->setIfExists('followUp', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('onCallReadiness', $data ?? [], null);
        $this->setIfExists('policyType', $data ?? [], null);
        $this->setIfExists('postMortem', $data ?? [], null);
        $this->setIfExists('schedule', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['conditions'] === null) {
            $invalidProperties[] = "'conditions' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['policyType'] === null) {
            $invalidProperties[] = "'policyType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets assignmentRules
     *
     * @return \IncidentIo\Model\PolicyAssignmentRulesPayloadV2|null
     */
    public function getAssignmentRules(): ?\IncidentIo\Model\PolicyAssignmentRulesPayloadV2
    {
        return $this->container['assignmentRules'];
    }

    /**
     * Sets assignmentRules
     *
     * @param \IncidentIo\Model\PolicyAssignmentRulesPayloadV2|null $assignmentRules assignmentRules
     *
     * @return $this
     */
    public function setAssignmentRules(?\IncidentIo\Model\PolicyAssignmentRulesPayloadV2 $assignmentRules): static
    {
        if (is_null($assignmentRules)) {
            throw new InvalidArgumentException('non-nullable assignmentRules cannot be null');
        }
        $this->container['assignmentRules'] = $assignmentRules;

        return $this;
    }

    /**
     * Gets conditions
     *
     * @return \IncidentIo\Model\ConditionGroupPayloadV2[]
     */
    public function getConditions(): array
    {
        return $this->container['conditions'];
    }

    /**
     * Sets conditions
     *
     * @param \IncidentIo\Model\ConditionGroupPayloadV2[] $conditions Conditions which determine which resources are in scope for this policy
     *
     * @return $this
     */
    public function setConditions(array $conditions): static
    {
        if (is_null($conditions)) {
            throw new InvalidArgumentException('non-nullable conditions cannot be null');
        }
        $this->container['conditions'] = $conditions;

        return $this;
    }

    /**
     * Gets debrief
     *
     * @return \IncidentIo\Model\PolicyDebriefPayloadV2|null
     */
    public function getDebrief(): ?\IncidentIo\Model\PolicyDebriefPayloadV2
    {
        return $this->container['debrief'];
    }

    /**
     * Sets debrief
     *
     * @param \IncidentIo\Model\PolicyDebriefPayloadV2|null $debrief debrief
     *
     * @return $this
     */
    public function setDebrief(?\IncidentIo\Model\PolicyDebriefPayloadV2 $debrief): static
    {
        if (is_null($debrief)) {
            throw new InvalidArgumentException('non-nullable debrief cannot be null');
        }
        $this->container['debrief'] = $debrief;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Human readable description of the policy
     *
     * @return $this
     */
    public function setDescription(string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets expressions
     *
     * @return \IncidentIo\Model\ExpressionPayloadV2[]|null
     */
    public function getExpressions(): ?array
    {
        return $this->container['expressions'];
    }

    /**
     * Sets expressions
     *
     * @param \IncidentIo\Model\ExpressionPayloadV2[]|null $expressions The expressions to use in this policy
     *
     * @return $this
     */
    public function setExpressions(?array $expressions): static
    {
        if (is_null($expressions)) {
            throw new InvalidArgumentException('non-nullable expressions cannot be null');
        }
        $this->container['expressions'] = $expressions;

        return $this;
    }

    /**
     * Gets followUp
     *
     * @return \IncidentIo\Model\PolicyFollowUpPayloadV2|null
     */
    public function getFollowUp(): ?\IncidentIo\Model\PolicyFollowUpPayloadV2
    {
        return $this->container['followUp'];
    }

    /**
     * Sets followUp
     *
     * @param \IncidentIo\Model\PolicyFollowUpPayloadV2|null $followUp followUp
     *
     * @return $this
     */
    public function setFollowUp(?\IncidentIo\Model\PolicyFollowUpPayloadV2 $followUp): static
    {
        if (is_null($followUp)) {
            throw new InvalidArgumentException('non-nullable followUp cannot be null');
        }
        $this->container['followUp'] = $followUp;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human readable name of the policy
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets onCallReadiness
     *
     * @return \IncidentIo\Model\PolicyOnCallReadinessV2|null
     */
    public function getOnCallReadiness(): ?\IncidentIo\Model\PolicyOnCallReadinessV2
    {
        return $this->container['onCallReadiness'];
    }

    /**
     * Sets onCallReadiness
     *
     * @param \IncidentIo\Model\PolicyOnCallReadinessV2|null $onCallReadiness onCallReadiness
     *
     * @return $this
     */
    public function setOnCallReadiness(?\IncidentIo\Model\PolicyOnCallReadinessV2 $onCallReadiness): static
    {
        if (is_null($onCallReadiness)) {
            throw new InvalidArgumentException('non-nullable onCallReadiness cannot be null');
        }
        $this->container['onCallReadiness'] = $onCallReadiness;

        return $this;
    }

    /**
     * Gets policyType
     *
     * @return string
     */
    public function getPolicyType(): string
    {
        return $this->container['policyType'];
    }

    /**
     * Sets policyType
     *
     * @param string $policyType Type of the policy, specifying what this applies to. Cannot be changed after the policy is created.
     *
     * @return $this
     */
    public function setPolicyType(string $policyType): static
    {
        if (is_null($policyType)) {
            throw new InvalidArgumentException('non-nullable policyType cannot be null');
        }
        $this->container['policyType'] = $policyType;

        return $this;
    }

    /**
     * Gets postMortem
     *
     * @return \IncidentIo\Model\PolicyPostMortemPayloadV2|null
     */
    public function getPostMortem(): ?\IncidentIo\Model\PolicyPostMortemPayloadV2
    {
        return $this->container['postMortem'];
    }

    /**
     * Sets postMortem
     *
     * @param \IncidentIo\Model\PolicyPostMortemPayloadV2|null $postMortem postMortem
     *
     * @return $this
     */
    public function setPostMortem(?\IncidentIo\Model\PolicyPostMortemPayloadV2 $postMortem): static
    {
        if (is_null($postMortem)) {
            throw new InvalidArgumentException('non-nullable postMortem cannot be null');
        }
        $this->container['postMortem'] = $postMortem;

        return $this;
    }

    /**
     * Gets schedule
     *
     * @return \IncidentIo\Model\PolicyScheduleV2|null
     */
    public function getSchedule(): ?\IncidentIo\Model\PolicyScheduleV2
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param \IncidentIo\Model\PolicyScheduleV2|null $schedule schedule
     *
     * @return $this
     */
    public function setSchedule(?\IncidentIo\Model\PolicyScheduleV2 $schedule): static
    {
        if (is_null($schedule)) {
            throw new InvalidArgumentException('non-nullable schedule cannot be null');
        }
        $this->container['schedule'] = $schedule;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Defaults to enabled on create. Settable on update — there is no separate disable endpoint.
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


