<?php
/**
 * ScheduleSyncTargetCreatePayloadV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * ScheduleSyncTargetCreatePayloadV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScheduleSyncTargetCreatePayloadV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScheduleSyncTargetCreatePayloadV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'addBotToGroup' => 'bool',
        'annotations' => 'array<string,string>',
        'newSlackUserGroup' => '\IncidentIo\Model\NewSlackUserGroupPayloadV2',
        'slackUserGroupId' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'addBotToGroup' => null,
        'annotations' => null,
        'newSlackUserGroup' => null,
        'slackUserGroupId' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'addBotToGroup' => false,
        'annotations' => false,
        'newSlackUserGroup' => false,
        'slackUserGroupId' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'addBotToGroup' => 'add_bot_to_group',
        'annotations' => 'annotations',
        'newSlackUserGroup' => 'new_slack_user_group',
        'slackUserGroupId' => 'slack_user_group_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'addBotToGroup' => 'setAddBotToGroup',
        'annotations' => 'setAnnotations',
        'newSlackUserGroup' => 'setNewSlackUserGroup',
        'slackUserGroupId' => 'setSlackUserGroupId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'addBotToGroup' => 'getAddBotToGroup',
        'annotations' => 'getAnnotations',
        'newSlackUserGroup' => 'getNewSlackUserGroup',
        'slackUserGroupId' => 'getSlackUserGroupId'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('addBotToGroup', $data ?? [], null);
        $this->setIfExists('annotations', $data ?? [], null);
        $this->setIfExists('newSlackUserGroup', $data ?? [], null);
        $this->setIfExists('slackUserGroupId', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['addBotToGroup'] === null) {
            $invalidProperties[] = "'addBotToGroup' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets addBotToGroup
     *
     * @return bool
     */
    public function getAddBotToGroup(): bool
    {
        return $this->container['addBotToGroup'];
    }

    /**
     * Sets addBotToGroup
     *
     * @param bool $addBotToGroup Whether the incident.io bot should be added to the group
     *
     * @return $this
     */
    public function setAddBotToGroup(bool $addBotToGroup): static
    {
        if (is_null($addBotToGroup)) {
            throw new InvalidArgumentException('non-nullable addBotToGroup cannot be null');
        }
        $this->container['addBotToGroup'] = $addBotToGroup;

        return $this;
    }

    /**
     * Gets annotations
     *
     * @return array<string,string>|null
     */
    public function getAnnotations(): ?array
    {
        return $this->container['annotations'];
    }

    /**
     * Sets annotations
     *
     * @param array<string,string>|null $annotations Annotations that track metadata about this resource
     *
     * @return $this
     */
    public function setAnnotations(?array $annotations): static
    {
        if (is_null($annotations)) {
            throw new InvalidArgumentException('non-nullable annotations cannot be null');
        }
        $this->container['annotations'] = $annotations;

        return $this;
    }

    /**
     * Gets newSlackUserGroup
     *
     * @return \IncidentIo\Model\NewSlackUserGroupPayloadV2|null
     */
    public function getNewSlackUserGroup(): ?\IncidentIo\Model\NewSlackUserGroupPayloadV2
    {
        return $this->container['newSlackUserGroup'];
    }

    /**
     * Sets newSlackUserGroup
     *
     * @param \IncidentIo\Model\NewSlackUserGroupPayloadV2|null $newSlackUserGroup newSlackUserGroup
     *
     * @return $this
     */
    public function setNewSlackUserGroup(?\IncidentIo\Model\NewSlackUserGroupPayloadV2 $newSlackUserGroup): static
    {
        if (is_null($newSlackUserGroup)) {
            throw new InvalidArgumentException('non-nullable newSlackUserGroup cannot be null');
        }
        $this->container['newSlackUserGroup'] = $newSlackUserGroup;

        return $this;
    }

    /**
     * Gets slackUserGroupId
     *
     * @return string|null
     */
    public function getSlackUserGroupId(): ?string
    {
        return $this->container['slackUserGroupId'];
    }

    /**
     * Sets slackUserGroupId
     *
     * @param string|null $slackUserGroupId Slack ID of an existing user group to sync to. Mutually exclusive with new_slack_user_group; exactly one must be set.
     *
     * @return $this
     */
    public function setSlackUserGroupId(?string $slackUserGroupId): static
    {
        if (is_null($slackUserGroupId)) {
            throw new InvalidArgumentException('non-nullable slackUserGroupId cannot be null');
        }
        $this->container['slackUserGroupId'] = $slackUserGroupId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


