<?php
/**
 * ScheduleSyncRuleV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * ScheduleSyncRuleV2 Class Doc Comment
 *
 * @description A sync rule links a schedule to a sync target, telling us which of the schedule&#39;s members should flow into the target&#39;s Slack user group.  sync_type decides who is synced: on_call syncs only the people currently on call, next_on_call syncs the people on the next upcoming shift, and all_users syncs everyone on the schedule. By default every rotation on the schedule is included; set rotation_id to scope the rule to a single rotation. As the schedule&#39;s shifts change hands, we keep the target&#39;s Slack user group membership in step with the rule.  A user group&#39;s members are the union of every rule feeding it, so one schedule can have several rules for the same target as long as they differ on rotation_id or sync_type. Point an on_call and a next_on_call rule at one group and it holds both the current and the next on-call.  permanent_member_user_ids names users who stay in the group whichever way the shifts fall, on top of whoever sync_type selects.
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScheduleSyncRuleV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScheduleSyncRuleV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'createdAt' => '\DateTime',
        'id' => 'string',
        'permanentMemberUserIds' => 'string[]',
        'rotationId' => 'string',
        'scheduleId' => 'string',
        'scheduleSyncTarget' => '\IncidentIo\Model\ScheduleSyncTargetResourceV2',
        'scheduleSyncTargetId' => 'string',
        'syncType' => 'string',
        'updatedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'createdAt' => 'date-time',
        'id' => null,
        'permanentMemberUserIds' => null,
        'rotationId' => null,
        'scheduleId' => null,
        'scheduleSyncTarget' => null,
        'scheduleSyncTargetId' => null,
        'syncType' => null,
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'createdAt' => false,
        'id' => false,
        'permanentMemberUserIds' => false,
        'rotationId' => false,
        'scheduleId' => false,
        'scheduleSyncTarget' => false,
        'scheduleSyncTargetId' => false,
        'syncType' => false,
        'updatedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'createdAt' => 'created_at',
        'id' => 'id',
        'permanentMemberUserIds' => 'permanent_member_user_ids',
        'rotationId' => 'rotation_id',
        'scheduleId' => 'schedule_id',
        'scheduleSyncTarget' => 'schedule_sync_target',
        'scheduleSyncTargetId' => 'schedule_sync_target_id',
        'syncType' => 'sync_type',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'createdAt' => 'setCreatedAt',
        'id' => 'setId',
        'permanentMemberUserIds' => 'setPermanentMemberUserIds',
        'rotationId' => 'setRotationId',
        'scheduleId' => 'setScheduleId',
        'scheduleSyncTarget' => 'setScheduleSyncTarget',
        'scheduleSyncTargetId' => 'setScheduleSyncTargetId',
        'syncType' => 'setSyncType',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'createdAt' => 'getCreatedAt',
        'id' => 'getId',
        'permanentMemberUserIds' => 'getPermanentMemberUserIds',
        'rotationId' => 'getRotationId',
        'scheduleId' => 'getScheduleId',
        'scheduleSyncTarget' => 'getScheduleSyncTarget',
        'scheduleSyncTargetId' => 'getScheduleSyncTargetId',
        'syncType' => 'getSyncType',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const SYNC_TYPE_ON_CALL = 'on_call';
    public const SYNC_TYPE_ALL_USERS = 'all_users';
    public const SYNC_TYPE_NEXT_ON_CALL = 'next_on_call';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getSyncTypeAllowableValues()
    {
        return [
            self::SYNC_TYPE_ON_CALL,
            self::SYNC_TYPE_ALL_USERS,
            self::SYNC_TYPE_NEXT_ON_CALL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('permanentMemberUserIds', $data ?? [], null);
        $this->setIfExists('rotationId', $data ?? [], null);
        $this->setIfExists('scheduleId', $data ?? [], null);
        $this->setIfExists('scheduleSyncTarget', $data ?? [], null);
        $this->setIfExists('scheduleSyncTargetId', $data ?? [], null);
        $this->setIfExists('syncType', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['permanentMemberUserIds'] === null) {
            $invalidProperties[] = "'permanentMemberUserIds' can't be null";
        }
        if ($this->container['scheduleId'] === null) {
            $invalidProperties[] = "'scheduleId' can't be null";
        }
        if ($this->container['scheduleSyncTarget'] === null) {
            $invalidProperties[] = "'scheduleSyncTarget' can't be null";
        }
        if ($this->container['scheduleSyncTargetId'] === null) {
            $invalidProperties[] = "'scheduleSyncTargetId' can't be null";
        }
        if ($this->container['syncType'] === null) {
            $invalidProperties[] = "'syncType' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier of the sync rule
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets permanentMemberUserIds
     *
     * @return string[]
     */
    public function getPermanentMemberUserIds(): array
    {
        return $this->container['permanentMemberUserIds'];
    }

    /**
     * Sets permanentMemberUserIds
     *
     * @param string[] $permanentMemberUserIds IDs of users always kept in the Slack user group, regardless of who is on call. Useful for keeping e.g. a manager in the group so they see mentions without being paged. Scoped to this rule: when several rules feed the same group, we sync the union of their permanent members.
     *
     * @return $this
     */
    public function setPermanentMemberUserIds(array $permanentMemberUserIds): static
    {
        if (is_null($permanentMemberUserIds)) {
            throw new InvalidArgumentException('non-nullable permanentMemberUserIds cannot be null');
        }
        $this->container['permanentMemberUserIds'] = $permanentMemberUserIds;

        return $this;
    }

    /**
     * Gets rotationId
     *
     * @return string|null
     */
    public function getRotationId(): ?string
    {
        return $this->container['rotationId'];
    }

    /**
     * Sets rotationId
     *
     * @param string|null $rotationId If set, only members of this rotation sync to the user group. When unset, all rotations on the schedule are synced.
     *
     * @return $this
     */
    public function setRotationId(?string $rotationId): static
    {
        if (is_null($rotationId)) {
            throw new InvalidArgumentException('non-nullable rotationId cannot be null');
        }
        $this->container['rotationId'] = $rotationId;

        return $this;
    }

    /**
     * Gets scheduleId
     *
     * @return string
     */
    public function getScheduleId(): string
    {
        return $this->container['scheduleId'];
    }

    /**
     * Sets scheduleId
     *
     * @param string $scheduleId The schedule this rule belongs to
     *
     * @return $this
     */
    public function setScheduleId(string $scheduleId): static
    {
        if (is_null($scheduleId)) {
            throw new InvalidArgumentException('non-nullable scheduleId cannot be null');
        }
        $this->container['scheduleId'] = $scheduleId;

        return $this;
    }

    /**
     * Gets scheduleSyncTarget
     *
     * @return \IncidentIo\Model\ScheduleSyncTargetResourceV2
     */
    public function getScheduleSyncTarget(): \IncidentIo\Model\ScheduleSyncTargetResourceV2
    {
        return $this->container['scheduleSyncTarget'];
    }

    /**
     * Sets scheduleSyncTarget
     *
     * @param \IncidentIo\Model\ScheduleSyncTargetResourceV2 $scheduleSyncTarget scheduleSyncTarget
     *
     * @return $this
     */
    public function setScheduleSyncTarget(\IncidentIo\Model\ScheduleSyncTargetResourceV2 $scheduleSyncTarget): static
    {
        if (is_null($scheduleSyncTarget)) {
            throw new InvalidArgumentException('non-nullable scheduleSyncTarget cannot be null');
        }
        $this->container['scheduleSyncTarget'] = $scheduleSyncTarget;

        return $this;
    }

    /**
     * Gets scheduleSyncTargetId
     *
     * @return string
     */
    public function getScheduleSyncTargetId(): string
    {
        return $this->container['scheduleSyncTargetId'];
    }

    /**
     * Sets scheduleSyncTargetId
     *
     * @param string $scheduleSyncTargetId The sync target ID this rule links to
     *
     * @return $this
     */
    public function setScheduleSyncTargetId(string $scheduleSyncTargetId): static
    {
        if (is_null($scheduleSyncTargetId)) {
            throw new InvalidArgumentException('non-nullable scheduleSyncTargetId cannot be null');
        }
        $this->container['scheduleSyncTargetId'] = $scheduleSyncTargetId;

        return $this;
    }

    /**
     * Gets syncType
     *
     * @return string
     */
    public function getSyncType(): string
    {
        return $this->container['syncType'];
    }

    /**
     * Sets syncType
     *
     * @param string $syncType Which schedule members sync to the user group
     *
     * @return $this
     */
    public function setSyncType(string $syncType): static
    {
        if (is_null($syncType)) {
            throw new InvalidArgumentException('non-nullable syncType cannot be null');
        }
        $this->container['syncType'] = $syncType;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt updatedAt
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


