<?php
/**
 * ScheduleCreatePayloadV2
 *
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use IncidentIo\ObjectSerializer;

/**
 * ScheduleCreatePayloadV2 Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScheduleCreatePayloadV2 implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScheduleCreatePayloadV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'annotations' => 'array<string,string>',
        'config' => '\IncidentIo\Model\ScheduleConfigCreatePayloadV2',
        'holidaysPublicConfig' => '\IncidentIo\Model\ScheduleHolidaysPublicConfigPayloadV2',
        'name' => 'string',
        'teamIds' => 'string[]',
        'timezone' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'annotations' => null,
        'config' => null,
        'holidaysPublicConfig' => null,
        'name' => null,
        'teamIds' => null,
        'timezone' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'annotations' => false,
        'config' => false,
        'holidaysPublicConfig' => false,
        'name' => false,
        'teamIds' => false,
        'timezone' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'annotations' => 'annotations',
        'config' => 'config',
        'holidaysPublicConfig' => 'holidays_public_config',
        'name' => 'name',
        'teamIds' => 'team_ids',
        'timezone' => 'timezone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'annotations' => 'setAnnotations',
        'config' => 'setConfig',
        'holidaysPublicConfig' => 'setHolidaysPublicConfig',
        'name' => 'setName',
        'teamIds' => 'setTeamIds',
        'timezone' => 'setTimezone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'annotations' => 'getAnnotations',
        'config' => 'getConfig',
        'holidaysPublicConfig' => 'getHolidaysPublicConfig',
        'name' => 'getName',
        'teamIds' => 'getTeamIds',
        'timezone' => 'getTimezone'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('annotations', $data ?? [], null);
        $this->setIfExists('config', $data ?? [], null);
        $this->setIfExists('holidaysPublicConfig', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('teamIds', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets annotations
     *
     * @return array<string,string>|null
     */
    public function getAnnotations(): ?array
    {
        return $this->container['annotations'];
    }

    /**
     * Sets annotations
     *
     * @param array<string,string>|null $annotations Annotations that can track metadata about the schedule
     *
     * @return $this
     */
    public function setAnnotations(?array $annotations): static
    {
        if (is_null($annotations)) {
            throw new InvalidArgumentException('non-nullable annotations cannot be null');
        }
        $this->container['annotations'] = $annotations;

        return $this;
    }

    /**
     * Gets config
     *
     * @return \IncidentIo\Model\ScheduleConfigCreatePayloadV2|null
     */
    public function getConfig(): ?\IncidentIo\Model\ScheduleConfigCreatePayloadV2
    {
        return $this->container['config'];
    }

    /**
     * Sets config
     *
     * @param \IncidentIo\Model\ScheduleConfigCreatePayloadV2|null $config config
     *
     * @return $this
     */
    public function setConfig(?\IncidentIo\Model\ScheduleConfigCreatePayloadV2 $config): static
    {
        if (is_null($config)) {
            throw new InvalidArgumentException('non-nullable config cannot be null');
        }
        $this->container['config'] = $config;

        return $this;
    }

    /**
     * Gets holidaysPublicConfig
     *
     * @return \IncidentIo\Model\ScheduleHolidaysPublicConfigPayloadV2|null
     */
    public function getHolidaysPublicConfig(): ?\IncidentIo\Model\ScheduleHolidaysPublicConfigPayloadV2
    {
        return $this->container['holidaysPublicConfig'];
    }

    /**
     * Sets holidaysPublicConfig
     *
     * @param \IncidentIo\Model\ScheduleHolidaysPublicConfigPayloadV2|null $holidaysPublicConfig holidaysPublicConfig
     *
     * @return $this
     */
    public function setHolidaysPublicConfig(?\IncidentIo\Model\ScheduleHolidaysPublicConfigPayloadV2 $holidaysPublicConfig): static
    {
        if (is_null($holidaysPublicConfig)) {
            throw new InvalidArgumentException('non-nullable holidaysPublicConfig cannot be null');
        }
        $this->container['holidaysPublicConfig'] = $holidaysPublicConfig;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of the schedule
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets teamIds
     *
     * @return string[]|null
     */
    public function getTeamIds(): ?array
    {
        return $this->container['teamIds'];
    }

    /**
     * Sets teamIds
     *
     * @param string[]|null $teamIds IDs of teams that own this schedule
     *
     * @return $this
     */
    public function setTeamIds(?array $teamIds): static
    {
        if (is_null($teamIds)) {
            throw new InvalidArgumentException('non-nullable teamIds cannot be null');
        }
        $this->container['teamIds'] = $teamIds;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone(): ?string
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone Timezone of the schedule
     *
     * @return $this
     */
    public function setTimezone(?string $timezone): static
    {
        if (is_null($timezone)) {
            throw new InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


