<?php
/**
 * IncidentAttachmentsV1Api
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use IncidentIo\ApiException;
use IncidentIo\Configuration;
use IncidentIo\HeaderSelector;
use IncidentIo\ObjectSerializer;

/**
 * IncidentAttachmentsV1Api Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IncidentAttachmentsV1Api
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'incidentAttachmentsV1Create' => [
            'application/json',
        ],
        'incidentAttachmentsV1Delete' => [
            'application/json',
        ],
        'incidentAttachmentsV1List' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation incidentAttachmentsV1Create
     *
     * Create Incident Attachments V1
     *
     * @param  \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1 incidentAttachmentsCreatePayloadV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Create'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \IncidentIo\Model\IncidentAttachmentsCreateResultV1|\IncidentIo\Model\ErrorResponse
     */
    public function incidentAttachmentsV1Create(
        \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1,
        string $contentType = self::contentTypes['incidentAttachmentsV1Create'][0]
    ): \IncidentIo\Model\IncidentAttachmentsCreateResultV1|\IncidentIo\Model\ErrorResponse
    {
        list($response) = $this->incidentAttachmentsV1CreateWithHttpInfo($incidentAttachmentsCreatePayloadV1, $contentType);
        return $response;
    }

    /**
     * Operation incidentAttachmentsV1CreateWithHttpInfo
     *
     * Create Incident Attachments V1
     *
     * @param  \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Create'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \IncidentIo\Model\IncidentAttachmentsCreateResultV1|\IncidentIo\Model\ErrorResponse, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function incidentAttachmentsV1CreateWithHttpInfo(
        \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1,
        string $contentType = self::contentTypes['incidentAttachmentsV1Create'][0]
    ): array
    {
        $request = $this->incidentAttachmentsV1CreateRequest($incidentAttachmentsCreatePayloadV1, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\IncidentAttachmentsCreateResultV1',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 408:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 412:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 413:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\IncidentIo\Model\IncidentAttachmentsCreateResultV1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\IncidentAttachmentsCreateResultV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 408:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation incidentAttachmentsV1CreateAsync
     *
     * Create Incident Attachments V1
     *
     * @param  \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Create'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1CreateAsync(
        \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1,
        string $contentType = self::contentTypes['incidentAttachmentsV1Create'][0]
    ): PromiseInterface
    {
        return $this->incidentAttachmentsV1CreateAsyncWithHttpInfo($incidentAttachmentsCreatePayloadV1, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incidentAttachmentsV1CreateAsyncWithHttpInfo
     *
     * Create Incident Attachments V1
     *
     * @param  \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Create'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1CreateAsyncWithHttpInfo(
        \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1,
        string $contentType = self::contentTypes['incidentAttachmentsV1Create'][0]
    ): PromiseInterface
    {
        $returnType = '\IncidentIo\Model\IncidentAttachmentsCreateResultV1';
        $request = $this->incidentAttachmentsV1CreateRequest($incidentAttachmentsCreatePayloadV1, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incidentAttachmentsV1Create'
     *
     * @param  \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Create'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incidentAttachmentsV1CreateRequest(
        \IncidentIo\Model\IncidentAttachmentsCreatePayloadV1 $incidentAttachmentsCreatePayloadV1,
        string $contentType = self::contentTypes['incidentAttachmentsV1Create'][0]
    ): Request
    {
        // verify the required parameter 'incidentAttachmentsCreatePayloadV1' is set
        if ($incidentAttachmentsCreatePayloadV1 === null || (is_array($incidentAttachmentsCreatePayloadV1) && count($incidentAttachmentsCreatePayloadV1) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $incidentAttachmentsCreatePayloadV1 when calling incidentAttachmentsV1Create'
            );
        }

        $resourcePath = '/v1/incident_attachments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($incidentAttachmentsCreatePayloadV1)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($incidentAttachmentsCreatePayloadV1), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $incidentAttachmentsCreatePayloadV1;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incidentAttachmentsV1Delete
     *
     * Delete Incident Attachments V1
     *
     * @param  string $id Unique identifier of this incident membership (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Delete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \IncidentIo\Model\ErrorResponse|null
     */
    public function incidentAttachmentsV1Delete(
        string $id,
        string $contentType = self::contentTypes['incidentAttachmentsV1Delete'][0]
    ): ?\IncidentIo\Model\ErrorResponse
    {
        list($response) = $this->incidentAttachmentsV1DeleteWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation incidentAttachmentsV1DeleteWithHttpInfo
     *
     * Delete Incident Attachments V1
     *
     * @param  string $id Unique identifier of this incident membership (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Delete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: null, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function incidentAttachmentsV1DeleteWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['incidentAttachmentsV1Delete'][0]
    ): array
    {
        $request = $this->incidentAttachmentsV1DeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 408:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation incidentAttachmentsV1DeleteAsync
     *
     * Delete Incident Attachments V1
     *
     * @param  string $id Unique identifier of this incident membership (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Delete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1DeleteAsync(
        string $id,
        string $contentType = self::contentTypes['incidentAttachmentsV1Delete'][0]
    ): PromiseInterface
    {
        return $this->incidentAttachmentsV1DeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incidentAttachmentsV1DeleteAsyncWithHttpInfo
     *
     * Delete Incident Attachments V1
     *
     * @param  string $id Unique identifier of this incident membership (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Delete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1DeleteAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['incidentAttachmentsV1Delete'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->incidentAttachmentsV1DeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incidentAttachmentsV1Delete'
     *
     * @param  string $id Unique identifier of this incident membership (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1Delete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incidentAttachmentsV1DeleteRequest(
        string $id,
        string $contentType = self::contentTypes['incidentAttachmentsV1Delete'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling incidentAttachmentsV1Delete'
            );
        }

        $resourcePath = '/v1/incident_attachments/{id}';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incidentAttachmentsV1List
     *
     * List Incident Attachments V1
     *
     * @param  string|null $incidentId Incident that this attachment is against (optional)
     * @param  string|null $externalId ID of the resource in the external system (optional)
     * @param  string|null $resourceType E.g. PagerDuty: the external system that holds the resource (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1List'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \IncidentIo\Model\IncidentAttachmentsListResultV1|\IncidentIo\Model\ErrorResponse
     */
    public function incidentAttachmentsV1List(
        ?string $incidentId = null,
        ?string $externalId = null,
        ?string $resourceType = null,
        string $contentType = self::contentTypes['incidentAttachmentsV1List'][0]
    ): \IncidentIo\Model\IncidentAttachmentsListResultV1|\IncidentIo\Model\ErrorResponse
    {
        list($response) = $this->incidentAttachmentsV1ListWithHttpInfo($incidentId, $externalId, $resourceType, $contentType);
        return $response;
    }

    /**
     * Operation incidentAttachmentsV1ListWithHttpInfo
     *
     * List Incident Attachments V1
     *
     * @param  string|null $incidentId Incident that this attachment is against (optional)
     * @param  string|null $externalId ID of the resource in the external system (optional)
     * @param  string|null $resourceType E.g. PagerDuty: the external system that holds the resource (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1List'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \IncidentIo\Model\IncidentAttachmentsListResultV1|\IncidentIo\Model\ErrorResponse, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function incidentAttachmentsV1ListWithHttpInfo(
        ?string $incidentId = null,
        ?string $externalId = null,
        ?string $resourceType = null,
        string $contentType = self::contentTypes['incidentAttachmentsV1List'][0]
    ): array
    {
        $request = $this->incidentAttachmentsV1ListRequest($incidentId, $externalId, $resourceType, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\IncidentAttachmentsListResultV1',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 408:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 412:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 413:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\IncidentIo\Model\IncidentAttachmentsListResultV1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\IncidentAttachmentsListResultV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 408:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation incidentAttachmentsV1ListAsync
     *
     * List Incident Attachments V1
     *
     * @param  string|null $incidentId Incident that this attachment is against (optional)
     * @param  string|null $externalId ID of the resource in the external system (optional)
     * @param  string|null $resourceType E.g. PagerDuty: the external system that holds the resource (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1List'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1ListAsync(
        ?string $incidentId = null,
        ?string $externalId = null,
        ?string $resourceType = null,
        string $contentType = self::contentTypes['incidentAttachmentsV1List'][0]
    ): PromiseInterface
    {
        return $this->incidentAttachmentsV1ListAsyncWithHttpInfo($incidentId, $externalId, $resourceType, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incidentAttachmentsV1ListAsyncWithHttpInfo
     *
     * List Incident Attachments V1
     *
     * @param  string|null $incidentId Incident that this attachment is against (optional)
     * @param  string|null $externalId ID of the resource in the external system (optional)
     * @param  string|null $resourceType E.g. PagerDuty: the external system that holds the resource (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1List'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function incidentAttachmentsV1ListAsyncWithHttpInfo(
        ?string $incidentId = null,
        ?string $externalId = null,
        ?string $resourceType = null,
        string $contentType = self::contentTypes['incidentAttachmentsV1List'][0]
    ): PromiseInterface
    {
        $returnType = '\IncidentIo\Model\IncidentAttachmentsListResultV1';
        $request = $this->incidentAttachmentsV1ListRequest($incidentId, $externalId, $resourceType, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incidentAttachmentsV1List'
     *
     * @param  string|null $incidentId Incident that this attachment is against (optional)
     * @param  string|null $externalId ID of the resource in the external system (optional)
     * @param  string|null $resourceType E.g. PagerDuty: the external system that holds the resource (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incidentAttachmentsV1List'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incidentAttachmentsV1ListRequest(
        ?string $incidentId = null,
        ?string $externalId = null,
        ?string $resourceType = null,
        string $contentType = self::contentTypes['incidentAttachmentsV1List'][0]
    ): Request
    {

        $resourcePath = '/v1/incident_attachments';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $incidentId,
            'incident_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $externalId,
            'external_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resourceType,
            'resource_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
