<?php
/**
 * TelemetryV2Api
 * PHP version 8.1
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * incident.io
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IncidentIo\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use IncidentIo\ApiException;
use IncidentIo\Configuration;
use IncidentIo\HeaderSelector;
use IncidentIo\ObjectSerializer;

/**
 * TelemetryV2Api Class Doc Comment
 *
 * @package  IncidentIo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TelemetryV2Api
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'telemetryV2UpdateDataSource' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation telemetryV2UpdateDataSource
     *
     * UpdateDataSource Telemetry V2
     *
     * @param  string $id Data source ID (required)
     * @param  \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2 telemetryUpdateDataSourcePayloadV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['telemetryV2UpdateDataSource'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \IncidentIo\Model\TelemetryUpdateDataSourceResultV2|\IncidentIo\Model\ErrorResponse
     */
    public function telemetryV2UpdateDataSource(
        string $id,
        \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2,
        string $contentType = self::contentTypes['telemetryV2UpdateDataSource'][0]
    ): \IncidentIo\Model\TelemetryUpdateDataSourceResultV2|\IncidentIo\Model\ErrorResponse
    {
        list($response) = $this->telemetryV2UpdateDataSourceWithHttpInfo($id, $telemetryUpdateDataSourcePayloadV2, $contentType);
        return $response;
    }

    /**
     * Operation telemetryV2UpdateDataSourceWithHttpInfo
     *
     * UpdateDataSource Telemetry V2
     *
     * @param  string $id Data source ID (required)
     * @param  \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['telemetryV2UpdateDataSource'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \IncidentIo\Model\TelemetryUpdateDataSourceResultV2|\IncidentIo\Model\ErrorResponse, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function telemetryV2UpdateDataSourceWithHttpInfo(
        string $id,
        \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2,
        string $contentType = self::contentTypes['telemetryV2UpdateDataSource'][0]
    ): array
    {
        $request = $this->telemetryV2UpdateDataSourceRequest($id, $telemetryUpdateDataSourcePayloadV2, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\TelemetryUpdateDataSourceResultV2',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 408:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 412:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 413:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\IncidentIo\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\IncidentIo\Model\TelemetryUpdateDataSourceResultV2',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\TelemetryUpdateDataSourceResultV2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 408:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IncidentIo\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation telemetryV2UpdateDataSourceAsync
     *
     * UpdateDataSource Telemetry V2
     *
     * @param  string $id Data source ID (required)
     * @param  \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['telemetryV2UpdateDataSource'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function telemetryV2UpdateDataSourceAsync(
        string $id,
        \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2,
        string $contentType = self::contentTypes['telemetryV2UpdateDataSource'][0]
    ): PromiseInterface
    {
        return $this->telemetryV2UpdateDataSourceAsyncWithHttpInfo($id, $telemetryUpdateDataSourcePayloadV2, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation telemetryV2UpdateDataSourceAsyncWithHttpInfo
     *
     * UpdateDataSource Telemetry V2
     *
     * @param  string $id Data source ID (required)
     * @param  \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['telemetryV2UpdateDataSource'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function telemetryV2UpdateDataSourceAsyncWithHttpInfo(
        string $id,
        \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2,
        string $contentType = self::contentTypes['telemetryV2UpdateDataSource'][0]
    ): PromiseInterface
    {
        $returnType = '\IncidentIo\Model\TelemetryUpdateDataSourceResultV2';
        $request = $this->telemetryV2UpdateDataSourceRequest($id, $telemetryUpdateDataSourcePayloadV2, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'telemetryV2UpdateDataSource'
     *
     * @param  string $id Data source ID (required)
     * @param  \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['telemetryV2UpdateDataSource'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function telemetryV2UpdateDataSourceRequest(
        string $id,
        \IncidentIo\Model\TelemetryUpdateDataSourcePayloadV2 $telemetryUpdateDataSourcePayloadV2,
        string $contentType = self::contentTypes['telemetryV2UpdateDataSource'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling telemetryV2UpdateDataSource'
            );
        }
        // verify the required parameter 'telemetryUpdateDataSourcePayloadV2' is set
        if ($telemetryUpdateDataSourcePayloadV2 === null || (is_array($telemetryUpdateDataSourcePayloadV2) && count($telemetryUpdateDataSourcePayloadV2) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $telemetryUpdateDataSourcePayloadV2 when calling telemetryV2UpdateDataSource'
            );
        }

        $resourcePath = '/v2/telemetry/data_sources/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($telemetryUpdateDataSourcePayloadV2)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($telemetryUpdateDataSourcePayloadV2), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $telemetryUpdateDataSourcePayloadV2;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
